openapi: "3.0.3"
info:
  title: Customer API documentation
  description: <p>PowerCARD Connect’API offers through APIs specific functions that group in a functional logic, all features relating to Client operations management.</p>
  version: PowerCARD-Issuer 3.5.4-apiR5.3
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:
  #getCorporateSelectedProducts   
  /getCorporateSelectedProducts/V2:
        post:
            description:
                        <h3>API Overview</h3>
                          <p>
                                 This web service can be used to get the list of products and packs that have been selected by a corporate for its employees. <br>
                                 The following sections are intended to highlight the process as well as the technical specification of the request and response messages.  
                          </p>
                        <h3>Functional Description</h3>
                         <img  src="./docs/getCorporateSelectedProducts.png" />
            summary: Get products and packs that have been selected by a corporate for its employees.
            tags:
              - Get Corporate Selected Products
            requestBody:
              required: true
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/GetCorporateSelectedProductsV35Rq'
                application/xml:
                  schema:
                    $ref: '#/components/schemas/GetCorporateSelectedProductsV35Rq'
            responses:  
              200:
                description:
                    <div>
                            Successful
                            <p>Business Error Codes &#58;</p>
                            <table>
                                  <tr>
                                    <th>Error code</th>
                                    <th>Error Description</th>
                                  </tr>
                                  <tr> 
                                    <td>30801</td>
                                    <td>Invalid Corporate Id</td>
                                  </tr>				
                            </table>
                    </div>
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/GetCorporateSelectedProductsV35Rs'
                  application/xml:
                    schema:
                      $ref: '#/components/schemas/GetCorporateSelectedProductsV35Rs'                             
# Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>      
  schemas:
    # --- Import getCorporateSelectedProductsV35Rq request and response
      GetCorporateSelectedProductsV35Rq:
               $ref: 'request.yaml#/getCorporateSelectedProductsV35Rq'  
      GetCorporateSelectedProductsV35Rs:
               $ref: 'response.yaml#/GetCorporateSelectedProductsV35Rs'  
security:
  - bearerAuth: []