openapi: "3.0.3"
info:
  title: Customer API documentation
  description: <p>PowerCARD Connect’API offers through APIs specific functions that group in a functional logic, all features relating to Client operations management.</p>
  version: PowerCARD-Issuer 3.5.4-apiR5.3
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:
  # --- GetCollaboratorInitiatedSubscription
  /GetCollaboratorInitiatedSubscription/V2:
        post:
            description:
                        <h3>API Overview</h3>
                          <a target="_blank" rel="noopener noreferrer" href="https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/jaxws/GetCollaboratorInitiatedSubscription/V2?wsdl"><img  src="./docs/soap_logo.jpg" /><u>SOAP WSDL</u></a>
                          <p>
                             This web service is used to initiate an employee subscription from the corporate portal.
                          </p>
                          <p>
                            The following sections are intended to highlight the process as well as the technical specification of the request and response messages.
                          </p>
                        <h3>Functional Description</h3>
                         <img  src="./docs/GetCollaboratorInitiatedSubscription.png" />
            summary: Initiate an employee subscription from the corporate portal.
            tags:
              - Get Collaborator Initiated Subscription.
            requestBody:
              required: true
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/GetCollaboratorInitiatedSubscriptionV35Rq'
                application/xml:
                  schema:
                    $ref: '#/components/schemas/GetCollaboratorInitiatedSubscriptionV35Rq'
            responses:  
              200:
                description:
                        <div>
                                Successful
                                <p>Business Error Codes &#58;</p>
                                <table>
                                    <tr>
                                      <th>Error code</th>
                                      <th>Error Description</th>
                                    </tr>
                                    <tr> 
                                      <td>31201</td>
                                      <td>Invalid Corporate ID</td>
                                    </tr>
                                    <tr> 
                                      <td>31202</td>
                                      <td>Invalid Employee ID</td>
                                    </tr>
                                    <tr> 
                                      <td>31203</td>
                                      <td>Invalid Subscription ID</td>
                                    </tr>								
                                </table>
                        </div> 
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/GetCollaboratorInitiatedSubscriptionV35Rs'
                  application/xml:
                    schema:
                      $ref: '#/components/schemas/GetCollaboratorInitiatedSubscriptionV35Rs'                                      
# Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>      
  schemas:
      GetCollaboratorInitiatedSubscriptionV35Rq:
            $ref: 'request.yaml#/GetCollaboratorInitiatedSubscriptionV35Rq'
      GetCollaboratorInitiatedSubscriptionV35Rs:
            $ref: 'response.yaml#/GetCollaboratorInitiatedSubscriptionV35Rs'    
security:
  - bearerAuth: []