openapi: "3.0.3"
info:
  title: Customer API documentation
  description: <p>PowerCARD Connect’API offers through APIs specific functions that group in a functional logic, all features relating to Client operations management.</p>
  version: PowerCARD-Issuer 3.5.4-apiR5.3
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:
  # --- UpdateCustomerName
  /UpdateCustomerName/V2:
        post:
            description:
                        <h3>API Overview</h3>
                          <a target="_blank" rel="noopener noreferrer" href="https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/jaxws/UpdateCustomerName/V2?wsdl"><img  src="./docs/soap_logo.jpg" /><u>SOAP WSDL</u></a>
                          <p>
                              Connect’API offers a selection of web services with regards to customer detail maintenance, the update person name web services is one of those services that can be used by both agents and customers in order to change the person name of an existing customer in the system.
                          </p>
                        <h3>Functional Description</h3>
                         <img  src="./docs/UpdateCustomerName.png" />
            summary: Change person name of an existing customer.
            tags:
              - Update Customer Name.
            requestBody:
              required: true
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/UpdateCustomerNameV35Rq'
                application/xml:
                  schema:
                    $ref: '#/components/schemas/UpdateCustomerNameV35Rq'
            responses:  
              200:
                description:
                        <div>
                                Successful
                                <p>Business Error Codes &#58;</p>
                                <table>
                                    <tr>
                                      <th>Error code</th>
                                      <th>Error Description</th>
                                    </tr>
                                    <tr> 
                                      <td>02301</td>
                                      <td>Invalid Customer Id</td>
                                    </tr>								
                                </table>
                        </div> 
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/UpdateCustomerNameV35Rs'
                  application/xml:
                    schema:
                      $ref: '#/components/schemas/UpdateCustomerNameV35Rs'                                           
# Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>      
  schemas:
      UpdateCustomerNameV35Rq:
            $ref: 'request.yaml#/UpdateCustomerNameV35Rq'
      UpdateCustomerNameV35Rs:
            $ref: 'response.yaml#/UpdateCustomerNameV35Rs'
security:
  - bearerAuth: []