openapi: "3.0.3"
info:
  title: Payment Instrument API documentation
  description: <p>Payment Instrument and Cardholder operation management include APIs for Payment Instrument maintenance , Payment instrument operations and Status operation.</p>
  version: PowerCARD-Issuer 3.5.4-apiR5.3
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:
  # ------- GetCardDetails API
  /GetCardDomainWebService/V2:
    post:
      description:  <h3>API Overview</h3>
        <p>The aim if this current web service is sharing the list of Domain control for a card. This list is sent back in the response message.
        
        As output the web service send back the result of the processing that could be either successfully or unsuccessfully, in what case, the system will share an error code and description for more details.</p>
        <h3>Functional Description</h3>
        <img  src="./docs/getCardDomain.png" />
      summary: Retrieve more details regarding the concerned card being sent in the request message.
      tags:
        - get Card Domain.
      requestBody:
        description: Retrieve more details regarding the concerned card being sent in the request message.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetCardDomainWebServiceV35Rq'
          application/xml:
            schema:
              $ref: '#/components/schemas/GetCardDomainWebServiceV35Rq'
      responses:
        200:
          description:
            <div>
            <h6>Successful</h6>
            <p>Business Error Codes &#58;</p>
            <table>
            <tr>
            <th>Error code</th>
            <th>Error Description</th>
            </tr>
            <tr>
            <td>21301</td>
            <td>Invalid Card Number/Token Id</td>
            </tr>
            </table>
            </div>
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetCardDomainWebServiceV35Rs'
            application/xml:
              schema:
                $ref: '#/components/schemas/GetCardDomainWebServiceV35Rs'

  # Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description:
        <div>
        <h5>Api key authorization</h5>
        <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
        <table>
        <tr>
        <td>Name &#8282;</td>
        <td>Authorization</td>
        </tr>
        <tr>
        <td>In &#8282;</td>
        <td>Header</td>
        </tr>
        <tr>
        <td>16701</td>
        <td>Invalid card number/Token.
        </td>
        </tr>
        <tr>
        <td>16702</td>
        <td>Process request is failed.
        </td>
        </tr>
        </table>
        </div>
  schemas:

    # ---- Import GetCardDetailsV35 request and response definition
    GetCardDomainWebServiceV35Rq:
      $ref: 'request.yaml#/GetCardDomainWebServiceV35Rq'
    GetCardDomainWebServiceV35Rs:
      $ref: 'response.yaml#/GetCardDomainWebServiceV35Rs'
security:
  - bearerAuth: []