openapi: "3.0.3"
info:
  title: Payment Instrument API documentation
  description: <p>Payment Instrument and Cardholder operation management include APIs for Payment Instrument maintenance , Payment instrument operations and Status operation.</p>
  version: PowerCARD-Issuer V4
servers:
  - url: https://api.wemeeting2023.pwcv4.com
    description: Development server
paths:
                              
 # ------- SetCardDetails API  
  /payment-instrument/v4.0/cards/set_cards_details:
    post:
      description:  <h3>API Overview</h3>
                      <p>The setCardDetails web service can be used by both agents and customers in order to update details regarding the concerned card being sent in the request message.</p>
                      <p>The setCardDetails web service includes the cardholder’s full name, embossed name, phones,  …
                      As output the web service send back the result of the processing that could be either successfully or unsuccessfully, in what case, the system will share an error code for investigation.
                      </p>
                    <h3>Functional Description</h3>
                    <img  src="./docs/SetCardDetails.png" />
      summary: This API can be used update details regarding the concerned card.
      tags:
        - Set Card Details
      requestBody:
        description: 
                <img id="select-case-img" src="./docs/exclamation.png" /> 
                <label  id="select-case">To make Connect'API protocol more extensible, an array of <b>key value</b> pairs is available in All object.</label>
                <label id="select-case"> for example to indicate to the PowerCARD Connect’API that the Alias PAN is being sent instead of the card number, the Client must include a key TOKEN with value Y &#58; </label>
                <code id="key-value-token"> 
                     {
                          ...
                          "keyValues" &#58; [{
                              "key" &#58; "token",
                              "data" &#58; "y"
                          }],
                          ...
                     }
                </code>        
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SetCardDetailsV4Rq'
          application/xml:
            schema:
              $ref: '#/components/schemas/SetCardDetailsV4Rq'
      responses:  
        200:
          description:
                  <div>
                  <p>Technical Error Codes &#58;</p>
                  <table>
                  <tr>
                  <th>Error code</th>
                  <th>Error Description</th>
                  </tr>
                  <tr>
                  <td>00000</td>
                  <td>Success</td>
                  </tr>
                  <tr>
                  <td>99999</td>
                  <td>System error</td>
                  </tr>
                  <tr>
                  <td>90009</td>
                  <td>Generic error for request validation failure (check size,format,mandatory etc..)</td>
                  </tr>
                  <tr>
                  <td>00002</td>
                  <td> Forbidden you don't have permission to access for this api</td>
                  </tr>
                  <tr>
                  <td>00007</td>
                  <td>Authorization header is empty</td>
                  </tr>
                  <tr>
                  <td>00008</td>
                  <td>Authorization header is missing</td>
                  </tr>
                  <tr>
                  <td>00009</td>
                  <td>Malformat Authorization content</td>
                  </tr>
                  <tr>
                  <td>00010</td>
                  <td>Bearer is required in the token</td>
                  </tr>
                  <tr>
                  <td>00011</td>
                  <td>Token expired</td>
                  </tr>
                  <tr>
                  <td>00012</td>
                  <td>Invalid token</td>
                  </tr>
                  <tr>
                  <td>00014</td>
                  <td>Invalid business date</td>
                  </tr>
                  <table>
                  <p>Business Error Codes &#58;</p>
                  <table>
                  <tr>
                  <th>Error code</th>
                  <th>Error Description <b>*</b></th>
                  </tr>
                    <tr>
                    <td>021301</td>
                    <td>Invalid CardNumber / TokenID</td>
                    </tr>
                    <tr>
                    <td>021302</td>
                    <td>Invalid bankCode</td>
                    </tr>
                  <tr>
                  <td>000220</td>
                  <td>BranchCode is not valid</td>
                  </tr>
                  <tr>
                  <td>000068</td>
                  <td>VipLevel is not valid</td>
                  </tr>
                  <tr>
                  <td>000219</td>
                  <td>NationalityCode is not valid</td>
                  </tr>
                  <tr>
                  <td>000211</td>
                  <td>Language is not valid</td>
                  </tr>
                  <tr>
                  <td>000212</td>
                  <td>Title code is not valid</td>
                  </tr>
                  <tr>
                  <td>000079</td>
                  <td>OwnerCode is not valid</td>
                  </tr>
                  <tr>
                  <td>000080</td>
                  <td>SocioProfessionalCode is not valid</td>
                  </tr>
                  <tr>
                  <td>000081</td>
                  <td>Activity code is not valid</td>
                  </tr>
                  <tr>
                  <td>000050</td>
                  <td>CustomerSegment is not valid</td>
                  </tr>
                  <tr>
                  <td>000139</td>
                  <td>PhoneType is not valid </td>
                  </tr>
                  <tr>
                  <td>000218</td>
                  <td>FieldName is not valid</td>
                  </tr>
                  </table>
                  </div>
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SetCardDetailsV4Rs'
            application/xml:
              schema:
                  $ref: '#/components/schemas/SetCardDetailsV4Rs' 

 # Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>      
  schemas:
    # --- Import SetCardDetailsV4 request and response.
      SetCardDetailsV4Rq:
                   $ref: 'request.yaml#/SetCardDetailsV4Rq'   
      SetCardDetailsV4Rs:
                  $ref: 'response.yaml#/SetCardDetailsV4Rs'           
security:
  - bearerAuth: []