openapi: "3.0.3"
info:
  title: Payment Tokenization API documentation
  description: <p>Tokenization allows users to store card information in ecommerce solutions and mobile wallets to allow the card to be recharged without exposing the original card information.Tokenization drives innovation. It’s the standard for the card transactions around the world, and PowerCARD Connect’ API system can adapt to sudden changes from emerging technology.</p>         
  version: PowerCARD-Issuer 3.5.4-apiR5.3
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:
  /v2/tokenRequestors/{tokenRequestorID}/wallets/{waletID}/cardMetadataNotificationService:
        post:
            description:
                        <h3>API Overview</h3>
                          <p>
                            This API is exposed by PowerCARD-Tokenization. TPL will invoke this API call when the issuer's Card Metadata has updated on the device by the wallet provider.
                          </p>
                        <h3>Functional Description</h3>
                        <img  src="./docs/cardMetadataNotificationService.png" />
            summary: Card Metadata are updated.
            tags:
              - Card Metadata Notification Service
            requestBody:
              required: true
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/CardMetadataNotificationServiceV35Rq'
                application/xml:
                  schema:
                    $ref: '#/components/schemas/CardMetadataNotificationServiceV35Rq'
            responses:  
              200:
                description:
                        <div>
                                Successful
                                <p>Business Error Codes &#58;</p>
                                <table>
                                        <tr>
                                        <th>Error code</th>
                                        <th>Error Description</th>
                                        <tr/>
                                        <tr>
                                        <td>T1101</td>
                                        <td>Invalid Wallet ID </td>
                                        <tr/>
                                        <tr>
                                        <td>T1102</td>
                                        <td>Invalid Token Requestor ID </td>
                                        <tr/>
                                        <tr>
                                        <td>T1103</td>
                                        <td>Invalid Correlation Invalid ID </td>
                                        <tr/>
                                        <tr>
                                        <td>T1104</td>
                                        <td>Invalid Token Reference ID </td>
                                        <tr/>
                                        <tr>
                                        <td>T1105</td>
                                        <td>Invalid Pan Reference ID </td>
                                        <tr/>
                                        <tr>
                                        <td>T1106</td>
                                        <td>Invalid Action Code </td>
                                        <tr/>
                                </table>
                        </div> 
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/CardMetadataNotificationServiceV35Rs'
                  application/xml:
                      schema:
                          $ref: '#/components/schemas/CardMetadataNotificationServiceV35Rs'
 # Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>      
  schemas:
        CardMetadataNotificationServiceV35Rq:
               $ref: 'request.yaml#/CardMetadataNotificationServiceV35Rq'
        CardMetadataNotificationServiceV35Rs:
               $ref: 'response.yaml#/CardMetadataNotificationServiceV35Rs'
security:
  - bearerAuth: []