server:
  servlet:
    context-path: /
spring:
  application:
    name: sandbox-ui
  mvc:
    static-path-pattern=/**
  flyway:
    enabled: true
    locations: classpath:db/migration
    validateOnMigrate: true
    baseline-on-migrate: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    hikari:
      auto-commit: false # delaying connection acquisition turn of auto commit mode
      connection-timeout: 30000
      idleTimeout: 600000
      max-lifetime: 1800000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        connection:
          provider_disables_autocommit: true # delaying hibernates connection acquisition ,turn of auto commit mode
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        generate_statistics: false
  h2:
    console:
      enabled: true
      path: /h2-console
  level:
    com:
      zaxxer:
        hikari: TRACE # turn on hikari connection pool logging ,each 30s logs the status of the connection pool in the console
    org:
      springframework:
        orm:
          jpa: debug #logging transaction details
        transaction: debug #logging transaction details
      hibernate:
        orm:
          jdbc:
            bind : trace # to display hibernate 6 binding parameters
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

