openapi: "3.0.3"
info:
  title: PowerCARD-Switch API documentation
  description: PowerCARD-Switch offers 100% availability with active/ active architecture, it is also able to process thousands of transactions per second. A performance expected in the mission-critical world of electronic payment transaction processing.
  version: PowerCARD 3.5.4-apiR5.3 
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths: 
#GetCardCharacteristics  
  /GetCardCharacteristics/V2:
        post:
            description:
                        <h3>API Overview</h3>
                          <p>
                          This web services can be used to get the card characteristics that have been already negotiated for a card.
                          </p>
                        <h3>Functional Description</h3>
                        <img  src="./docs/GetCardCharacteristics.png" />
            summary: Get the card characteristics that have been already negotiated for a card.
            tags:
              - Get Card Characteristics
            requestBody:
              required: true
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/GetCardCharacteristicsV35Rq'
                application/xml:
                  schema:
                    $ref: '#/components/schemas/GetCardCharacteristicsV35Rq'
            responses:  
              200:
                description:
                        <div>
                                Successful
                                <p>Business Error Codes &#58;</p>
                                <table>
                                      <tr>
                                        <th>Error code</th>
                                        <th>Error Description</th>
                                      </tr>
                                      <tr>
                                          <td>30301</td>
                                          <td>Invalid Card Number/ Token Id </td>
                                      </tr>
                                </table>
                        </div> 
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/GetCardCharacteristicsV35Rs'
                  application/xml:
                          schema:
                              $ref: '#/components/schemas/GetCardCharacteristicsV35Rs'       
# Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>      
  schemas:
    # --- Import DemoV35 request and response
      GetCardCharacteristicsV35Rq:
               $ref: 'request.yaml#/GetCardCharacteristicsV35Rq'
      GetCardCharacteristicsV35Rs:
               $ref: 'response.yaml#/GetCardCharacteristicsV35Rs' 
  security:
  - bearerAuth: []
