openapi: "3.0.3"
info:
  title: Payment Instrument API documentation
  description: <p>Payment Instrument and Cardholder operation management include APIs for Payment Instrument maintenance , Payment instrument operations and Status operation.</p>
  version: PowerCARD-Issuer 3.5.4-apiR5.3
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:

  # --- /AddMerchantSite/V3
  /AddMerchantSite/V3:
    post:
      description:
        <h3>API Overview</h3>
        <p>
        The add merchant site API provides functionality to add a merchant site details during a merchant enrollment process. The merchant site details must contain information like site name and location…
        </p>
        <h3>Functional Description</h3>
        <img  src="./docs/addMerchantSite.png" />
      summary:   A debit card allows the cardholder access to a source of funding that is linked to his/her card.
      tags:
        - Add Merchant Site
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddMerchantSiteRq'
          application/xml:
            schema:
              $ref: '#/components/schemas/AddMerchantSiteRq'
      responses:
        200:
          description:
            <div>
            Successful
            <p>Business Error Codes &#58;</p>
            <table>
            <tr>
            <th>Error Code</th>
            <th>Description</th>
            </tr>
            </thead>
            <tbody>
            <tr>
            <td>40100</td>
            <td>Invalid Merchant Bank Code</td>
            </tr>
            <tr>
            <td>40136</td>
            <td>You should specify at least one on this fields:<b> Merchant ID or legal ID</td>
            </tr>
            <tr>
            <td>40200</td>
            <td>Merchant not found</td>
            </tr>
            <tr>
            <td>40307</td>
            <td>Invalid Address Country Code</td>
            </tr>
            <tr>
            <td>40308</td>
            <td>Invalid Address Zip Code</td>
            </tr>
            <tr>
            <td>40309</td>
            <td>Invalid Address Region Code</td>
            </tr>
            <tr>
            <td>40310</td>
            <td>Invalid Address City Code</td>
            </tr>
            <tr>
            <td>40311</td>
            <td>Invalid Address Phone Type</td>
            </tr>
            <tr>
            <td>40314</td>
            <td>Invalid Address URL</td>
            </tr>
            <tr>
            <td>40320</td>
            <td>Force ZIPCode not allowed on bank addendum params</td>
            </tr>
            <tr>
            <td>40322</td>
            <td>Invalid address city name</td>
            </tr>
            <tr>
            <td>40410</td>
            <td>Bank addendum not found</td>
            </tr>
            <tr>
            <td>40600</td>
            <td>Invalid Site Type</td>
            </tr>
            <tr>
            <td>40601</td>
            <td>Invalid Site Opening date</td>
            </tr>
            <tr>
            <td>40605</td>
            <td>Invalid Site Status Start date</td>
            </tr>
            <tr>
            <td>40606</td>
            <td>Invalid Site Status End date</td>
            </tr>
            <tr>
            <td>40607</td>
            <td>Error while generating merchant acquiring site id</td>
            </tr>
            <tr>
            <td>40610</td>
            <td>The merchant already has a primary site</td>
            </tr>
            <tr>
            <td>40612</td>
            <td>Error while inserting site information’s</td>
            </tr>
            
            
            </table>
            </div>
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddMerchantSiteRs'
            application/xml:
              schema:
                $ref: '#/components/schemas/AddMerchantSiteRs'
  # Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description:
        <div>
        <h5>Api key authorization</h5>
        <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
        <table>
        <tr>
        <td>Name &#8282;</td>
        <td>Authorization</td>
        </tr>
        <tr>
        <td>In &#8282;</td>
        <td>Header</td>
        </tr>
        </table>
        </div>
  schemas:

    # --- Import CreateDebitCardV35 request and response
    AddMerchantSiteRq:
      $ref: 'request.yaml#/AddMerchantSiteRq'
    AddMerchantSiteRs:
      $ref: 'response.yaml#/AddMerchantSiteRs'
security:
  - bearerAuth: []