openapi: "3.0.3"
info:
  title: Payment Instrument API documentation
  description: <p>Payment Instrument and Cardholder operation management include APIs for Payment Instrument maintenance , Payment instrument operations and Status operation.</p>
  version: PowerCARD-Issuer 3.5.4-apiR5.3
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:

  # --- /UpdateMerchantBankAccount/V3
  /UpdateMerchantBankAccount/V3:
    post:
      description:
        <h3>API Overview</h3>
        <p>
        The present web service is aimed to be used whenever any user would like to change a detail of a merchant bank account information in the system. Whenever it is requested to do, users need to provide information with regards to the merchant account number, status… so that PowerCARD can proceed and change accordingly.
        </p>
        <h3>Functional Description</h3>
        <img  src="./docs/updateMerchantBankAccount.png" />
      summary:   A debit card allows the cardholder access to a source of funding that is linked to his/her card.
      tags:
        - Update Merchant BankAccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateMerchantBankAccountRq'
          application/xml:
            schema:
              $ref: '#/components/schemas/UpdateMerchantBankAccountRq'
      responses:
        200:
          description:
            <div>
            Successful
            <p>Business Error Codes &#58;</p>
            <table>
            <tr>
            <th>Error Code</th>
            <th>Description</th>
            </tr>
            <tr><td>40100</td><td>Invalid Merchant Bank Code</td></tr>
            <tr><td>40136</td><td>You should specify at least one on this fields:<b> Merchant ID or legal ID</td></tr>
            <tr><td>40200</td><td>Merchant not found</td></tr>
            <tr><td>40500</td><td>Invalid account sequence ID</td></tr>
            <tr><td>40501</td><td>Invalid Account Type</td></tr>
            <tr><td>40502</td><td>Invalid Account category</td></tr>
            <tr><td>40503</td><td>Invalid Account Bank code</td></tr>
            <tr><td>40504</td><td>Invalid Account Branch code</td></tr>
            <tr><td>40505</td><td>Invalid Account chain bank code</td></tr>
            <tr><td>40506</td><td>Invalid Account chain code</td></tr>
            <tr><td>40507</td><td>Invalid Account Number</td></tr>
            <tr><td>40508</td><td>Invalid Account Currency</td></tr>
            <tr><td>40510</td><td>Invalid Account  Remittance Grouping</td></tr>
            <tr><td>40511</td><td>Invalid Account Fees Grouping</td></tr>
            <tr><td>40512</td><td>Invalid Account  Chargeback Grouping</td></tr>
            <tr><td>40513</td><td>Invalid Account  Billable Element Grouping</td></tr>
            <tr><td>40515</td><td>Error while update merchant account</td></tr>
            <tr><td>40518</td><td>The merchant already has a primary account</td></tr>
            <tr><td>40519</td><td>Account number already exist</td></tr>
            <tr><td>40138</td><td>Normal, suspended, under surveillance are the status needed to allow updating</td></tr>
            
            </table>
            </div>
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateMerchantBankAccountRs'
            application/xml:
              schema:
                $ref: '#/components/schemas/UpdateMerchantBankAccountRs'
  # Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description:
        <div>
        <h5>Api key authorization</h5>
        <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
        <table>
        <tr>
        <td>Name &#8282;</td>
        <td>Authorization</td>
        </tr>
        <tr>
        <td>In &#8282;</td>
        <td>Header</td>
        </tr>
        </table>
        </div>
  schemas:

    # --- Import ValidateMercchantRs request and response
    UpdateMerchantBankAccountRq:
      $ref: 'request.yaml#/UpdateMerchantBankAccountRq'
    UpdateMerchantBankAccountRs:
      $ref: 'response.yaml#/UpdateMerchantBankAccountRs'
security:
  - bearerAuth: []