openapi: "3.0.3"
info:
  title: Payment Instrument API documentation
  description: <p>Payment Instrument and Cardholder operation management include APIs for Payment Instrument maintenance , Payment instrument operations and Status operation.</p>
  version: PowerCARD-Issuer 3.5.4-apiR5.3
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:

  # --- /GetMerchantContractDetails /V3
  /GetMerchantContractDetails/V3:
    post:
      description:
        <h3>API Overview</h3>
        <p>
        The aim of this Web service is to retrieve data related to a given merchant contract as defined under the PowerCARD merchant management system. Details are stored in multiple PowerCARD tables, they are all processed then returned back in the response message.
        <h3>Functional Description</h3>
        <img  src="./docs/GetMerchantContractDetails.png" />
      summary:   A debit card allows the cardholder access to a source of funding that is linked to his/her card.
      tags:
        - Get Merchant Contract Details
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetMerchantContractDetailsRq'
          application/xml:
            schema:
              $ref: '#/components/schemas/GetMerchantContractDetailsRq'
      responses:
        200:
          description:
            <div>
            Successful
            <p>Business Error Codes &#58;</p>
            <table>
            <tr><td>60100</td><td>Invalid Merchant Bank Code</td></tr>
            <tr><td>60136</td><td>You should specify at least one on this fields:<b> Merchant ID or legal ID<b/></td></tr>
            <tr><td>60200</td><td>Merchant not found</td></tr>
            <tr><td>61300</td><td>Invalid Contract ID</td></tr>
            
            
            
            </table>
            </div>
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMerchantContractDetailsRs'
            application/xml:
              schema:
                $ref: '#/components/schemas/GetMerchantContractDetailsRs'
  # Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description:
        <div>
        <h5>Api key authorization</h5>
        <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
        <table>
        <tr>
        <td>Name &#8282;</td>
        <td>Authorization</td>
        </tr>
        <tr>
        <td>In &#8282;</td>
        <td>Header</td>
        </tr>
        </table>
        </div>
  schemas:

    # --- Import DeactivateMerchantContractRq request and response
    GetMerchantContractDetailsRq:
      $ref: 'request.yaml#/GetMerchantContractDetailsRq'
    GetMerchantContractDetailsRs:
      $ref: 'response.yaml#/GetMerchantContractDetailsRs'
security:
  - bearerAuth: []