create table sa_api (
                            api_id integer generated by default as identity,
                            module_id integer,
                            description varchar(255),
                            link varchar(255),
                            name varchar(255),
                            primary key (api_id)
);