openapi: "3.0.3"
info:
  title: PowerCARD-Switch API documentation
  description: PowerCARD-Switch offers 100% availability with active/ active architecture, it is also able to process thousands of transactions per second. A performance expected in the mission-critical world of electronic payment transaction processing.
  version: PowerCARD 3.5.4-apiR5.3 
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths: 
  # ------- getAuthorizationDetails
  /GetAuthorizationDetails/V2:
    post:
      description:  <h3>API Overview</h3>
                    <p>The get authorization details web service is an aggregated view of an authorization data managed by the system. This service provides the ability to get details for a specific authorization in the system using the Reference Number and other fields, fields used internally by PowerCARD to identify uniquely an authorization in the system. In addition to the authorization information, this API provides information data relating to the card, account, credit …</p>
                    <h3>Functional Description</h3>
                    <img  src="./docs/getAuthorizationDetails.png" />
                  
      summary: Aggregated view of an authorization data managed by the system.
      tags:
        - Get Authorization Details
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetAuthorizationDetailsV35Rq'
          application/xml:
            schema:
              $ref: '#/components/schemas/GetAuthorizationDetailsV35Rq'
      responses:  
         200:
          description:
                        <div>
                                Successful
                                <p>Business Error Codes &#58;</p>
                                <table>
                                    <tr>
                                      <th>Error code</th>
                                      <th>Error Description</th>
                                    </tr>
                                    <tr> 
                                      <td>18401</td>
                                      <td>Invalid Range Date</td>
                                    </tr>	
                                    <tr> 
                                      <td>18402</td>
                                      <td>Invalid Data Source</td>
                                    </tr>	
                                    <tr> 
                                      <td>18404</td>
                                      <td>Invalid Action Code</td>
                                    </tr>	
                                    <tr> 
                                      <td>18405</td>
                                      <td>Invalid Processing Code</td>
                                    </tr>	
                                    <tr> 
                                      <td>18406</td>
                                      <td>Invalid Transaction Amount</td>
                                    </tr>	 
                                    <tr> 
                                      <td>18407</td>
                                      <td>Invalid Message Type</td>
                                    </tr>	  
                                    <tr> 
                                      <td>18408</td>
                                      <td>Invalid Authorization Type</td>
                                    </tr>	                                                                                                                                                                                                                         							
                                </table>
                        </div> 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAuthorizationDetailsV35Rs' 
            application/xml:
                    schema:
                        $ref: '#/components/schemas/GetAuthorizationDetailsV35Rs'
# Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>      
  schemas:
      GetAuthorizationDetailsV35Rq:
               $ref: 'request.yaml#/GetAuthorizationDetailsV35Rq'
      GetAuthorizationDetailsV35Rs:
               $ref: 'response.yaml#/GetAuthorizationDetailsV35Rs'
  security:
  - bearerAuth: []
