openapi: "3.0.3"
info:
  title: PowerCARD-Switch API documentation
  description: PowerCARD-Switch offers 100% availability with active/ active architecture, it is also able to process thousands of transactions per second. A performance expected in the mission-critical world of electronic payment transaction processing.
  version: PowerCARD 3.5.4-apiR5.3 
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths: 
  #/Cards/V2/{aliasPAN}/Domain                  
  /Cards/V2/{aliasPAN}/Domain:
        get:
            description:
                        <h3>API Overview</h3>
                          <p>
                              The aim if this current web service is sharing the list of Domain control for a card. This list is sent back in the response message.
                          </p>
                          <p>
                             As output the web service send back the result of the processing that could be either successfully or unsuccessfully, in what case, the system will share an error code and description for more details.
                          </p>
                        <h3>Functional Description</h3>
                        <img  src="./docs/GetCardDomain.png" />
            summary:     This web service is mainly used to retrieve list of Domain control for a card.
            tags:
              - Get Card Domain
            parameters:
              - in: path
                name: aliasPAN
                schema:
                  type: string
                required: true
                description: AliasPAN String to get card details.
              - in: query
                name: requestUID 
                schema:
                  type: string
                description: Request Identifier. It is sent by the calling system as a universally unique identifier for the message. Used to match response with request messages.
              - in: query
                name: requestDate 
                schema:
                  type: string
                description: Date when the request was submitted.
              - in: query
                name: userID 
                schema:
                  type: string
                description: Represents the user Id who made the request.
            responses:  
              200:
                description:
                        <div>
                                Successful
                                <p>Business Error Codes &#58;</p>
                                <table>
                                      <tr>
                                        <th>Error code</th>
                                        <th>Error Description</th>
                                      </tr>
                                      <tr> 
                                        <td>16701</td>
                                        <td>Invalid Card Number/Token Id</td>
                                      </tr>	
                                      <tr> 
                                        <td>16702</td>
                                        <td>Process request is failed</td>
                                      </tr>								
                                </table>
                        </div> 
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/GetCardDomainV35Rs'
                  application/xml:
                      schema:
                          $ref: '#/components/schemas/GetCardDomainV35Rs'  
# Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>      
  schemas:
    # --- Import GetCardDomainV35 request and response definition 
      GetCardDomainV35Rq:
            $ref: 'request.yaml#/GetCardDomainV35Rq'
      GetCardDomainV35Rs:
            $ref: 'response.yaml#/GetCardCVC2V35Rs'
  security:
  - bearerAuth: []
