openapi: "3.0.3"
info:
  title: PowerCARD-Switch API documentation
  description: PowerCARD-Switch offers 100% availability with active/ active architecture, it is also able to process thousands of transactions per second. A performance expected in the mission-critical world of electronic payment transaction processing.
  version: PowerCARD 3.5.4-apiR5.3 
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:

 # ------- TokenAuthentication API  

  /TokenAuthentication:
    post:
      description:  <h3>API Overview</h3>
                    <a target="_blank" rel="noopener noreferrer" href="https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/jaxws/TokenAuthentication?wsdl"><img  src="./docs/soap_logo.jpg" /><u>SOAP WSDL</u></a>                    <p>PowerCard Connect'API uses JWT authentication for securing the exposed REST APIs, the user will be able to consume API TokenAuthentification only if it has a valid Token.</p>
                    <p>The Connect’API authenticates all requests using the token available in the request itself, If such an authentication fails, Connect’API simply sends an HTTP code 401 (Unauthorized).</p>
                    <h3>Functional Description</h3>
                    <img  src="./docs/tokenAuthentication.png" />
      summary: Token Authentication service using user credentials. 
      tags:
        - User Token Authentication.
      requestBody:
        description: Token Authentication service using user credentials.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenAuthentication'
          application/xml:
            schema:
              $ref: '#/components/schemas/TokenAuthentication'      
      responses:
        200:
          description:
                  <div>
                          Successful
                          <p>Business Error Codes &#58;</p>
                           <table>
                              <tr>
                                <th>Error code</th>
                                <th>Error Description</th>
                              </tr>
                              <tr> 
                                <td>00000</td>
                                <td>Success</td>
                              </tr>	
                              <tr> 
                                <td>00001</td>
                                <td>System Error</td>
                              </tr>	
                              <tr> 
                                <td>00002</td>
                                <td>Invalid RqUID</td>
                              </tr>	
                              <tr> 
                                <td>00003</td>
                                <td>Authentication failed</td>
                              </tr>	
                              <tr> 
                                <td>00004</td>
                                <td>Unknown product</td>
                              </tr>	
                              <tr> 
                                <td>00005</td>
                                <td>Unknown language</td>
                              </tr>	
                              <tr> 
                                <td>00006</td>
                                <td>Invalid customer information</td>
                              </tr>
                              <tr> 
                                <td>00007</td>
                                <td>Invalid pagination step</td>
                              </tr>	
                              <tr> 
                                <td>00008</td>
                                <td>Access to the bank id data is denied</td>
                              </tr>	
                              <tr> 
                                <td>00010</td>
                                <td>Invalid Provider Data</td>
                              </tr>	
                              <tr> 
                                <td>00011</td>
                                <td>Invalid message</td>
                              </tr>	
                              <tr> 
                                <td>00012</td>
                                <td>User is blocked</td>
                              </tr>	
                              <tr> 
                                <td>00013</td>
                                <td>Account is deactivated</td>
                              </tr>	
                              <tr> 
                                <td>00014</td>
                                <td>Operation already performed</td>
                              </tr>	
                              <tr> 
                                <td>00020</td>
                                <td>Password Expired</td>
                              </tr>	
                              <tr> 
                                <td>00030</td>
                                <td>Waiting for validation</td>
                              </tr>	
                              <tr> 
                                <td>00040</td>
                                <td>Error when retrieving interface information</td>
                              </tr>	
                              <tr> 
                                <td>00041</td>
                                <td>Error when retrieving card information</td>
                              </tr>	
                              <tr> 
                                <td>00042</td>
                                <td>Error when retrieving token information</td>
                              </tr>	
                              <tr> 
                                <td>00043</td>
                                <td>Error while generating the token</td>
                              </tr>	
                              <tr> 
                                <td>00044</td>
                                <td>Error while inserting token information</td>
                              </tr>	
                              <tr> 
                                <td>00099</td>
                                <td>Invalid range date</td>
                              </tr>	
                              <tr> 
                                <td>99999</td>
                                <td>Database exception error</td>
                              </tr>									
                           </table>
                  </div> 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenAuthenticationResponse'
            application/xml:
                      schema:
                          $ref: '#/components/schemas/TokenAuthenticationResponse'  
# Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>      
  schemas:
      # ---- Import TokenAuthentication request and response definition            
      TokenAuthentication:
            $ref: 'request.yaml#/TokenAuthentication'
      TokenAuthenticationResponse:
            $ref: 'response.yaml#/TokenAuthenticationResponse'
  security:
  - bearerAuth: []
