openapi: "3.0.3"
info:
  title: PowerCARD-Switch API documentation
  description: PowerCARD-Switch offers 100% availability with active/ active architecture, it is also able to process thousands of transactions per second. A performance expected in the mission-critical world of electronic payment transaction processing.
  version: PowerCARD 3.5.4-apiR5.3 
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:
  # ------- verifyPIN 
  /VerifyPin/V2:
    post:
      description:  <h3>API Overview</h3>
                    <p>The verify PIN web service is used to verify if the Personal Identification Number (PIN) introduced is valid or not. Users must transmit different details in the request that are used internally by PowerCARD to communicate with the HSM to validate the PIN captured by the customer. Depending on the validation processes, the response message that will be returned will either contain a Yes or No. Yes to specify that the PIN captured is valid, and No in the opposite case.</b></p>
                    <h3>Functional Description</h3>
                    <img  src="./docs/verifyPin.png" />
      summary: The verify PIN web service is used to verify if the Personal Identification Number (PIN)...
      tags:
        - VerifyPIN
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerifyPinRq'
          application/xml:
            schema:
              $ref: '#/components/schemas/VerifyPinRq'
      responses:  
         200:
          description:
                  <div>
                          Successful
                          <p>Business Error Codes &#58;</p>
                           <table>
                              <tr>
                                <th>Error code</th>
                                <th>Error Description</th>
                              </tr>
                              <tr> 
                                <td>18001</td>
                                <td>Invalid Card number</td>
                              </tr>	
                              <tr> 
                                <td>18002</td>
                                <td>Invalid PIN Block</td>
                              </tr>	
                              <tr> 
                                <td>18003</td>
                                <td>Invalid Pin method</td>
                              </tr>
                              <tr> 
                                <td>18004</td>
                                <td>Card do not belong to any range in the system</td>
                              </tr>	
                              <tr> 
                                <td>18005</td>
                                <td>Error while getting PVK Keys</td>
                              </tr>	
                              <tr> 
                                <td>18006</td>
                                <td>Error while Verifying Visa PIN</td>
                              </tr>	
                              <tr> 
                                <td>18007</td>
                                <td>Error while Verifying IBM PIN</td>
                              </tr>	
                           </table>
                  </div> 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerifyPinRs'
            application/xml:
                      schema:
                          $ref: '#/components/schemas/VerifyPinRs'
# Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>      
  schemas:
    # --- Import VerifyPin request and response
      VerifyPinRq:
               $ref: 'request.yaml#/VerifyPinRq'
      VerifyPinRs:
               $ref: 'response.yaml#/VerifyPinRs'
  security:
  - bearerAuth: []
