openapi: "3.0.3"
info:
  title: Payment Instrument API documentation
  description: <p>Payment Instrument and Cardholder operation management include APIs for Payment Instrument maintenance , Payment instrument operations and Status operation.</p>
  version: PowerCARD-Issuer 3.5.4-apiR5.3
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:

  # --- /GetSummaryCardTransactions /V2
  /GetSummaryCardTransactions/V2:
    post:
      description:
        <h3>API Overview</h3>
        <p>
        This web service can be used to retrieve the summary of card transactions.

        Corporate may use different criteria to retrieve this summary.

        Criteria’s could include Corporate id, card number, dates…

        As output the web service returns the result of the processing that could be either successfully or unsuccessfully, in what case, the system will share an error code for investigation.
        <img  src="./docs/getSummaryCardTransactions.png" />
      summary:   A debit card allows the cardholder access to a source of funding that is linked to his/her card.
      tags:
        - Get Summary Card Transactions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetSummaryCardTransactionsRq'
          application/xml:
            schema:
              $ref: '#/components/schemas/GetSummaryCardTransactionsRq'
      responses:
        200:
          description:
            <div>
            Successful
            <p>Business Error Codes &#58;</p>
            <table>
            
            <tr><td>50001</td><td>Invalid Corporate Id</td></tr>
            <tr><td>50002</td><td>Invalid Range Date</td></tr>
            <tr><td>50003</td><td>Invalid First Name</td></tr>
            <tr><td>50004</td><td>Invalid Last Name</td></tr>
            <tr><td>50005</td><td>Invalid Card Number/Token Id</td></tr>
            <tr><td>50006</td><td>Invalid Direct Debit Option</td></tr>
            
            
            </table>
            </div>
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetSummaryCardTransactionsRs'
            application/xml:
              schema:
                $ref: '#/components/schemas/GetSummaryCardTransactionsRs'
  # Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description:
        <div>
        <h5>Api key authorization</h5>
        <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
        <table>
        <tr>
        <td>Name &#8282;</td>
        <td>Authorization</td>
        </tr>
        <tr>
        <td>In &#8282;</td>
        <td>Header</td>
        </tr>
        </table>
        </div>
  schemas:

    # --- Import GetSummaryCardTransactions request and response
    GetSummaryCardTransactionsRq:
      $ref: 'request.yaml#/GetSummaryCardTransactionsRq'
    GetSummaryCardTransactionsRs:
      $ref: 'response.yaml#/GetSummaryCardTransactionsRs'
security:
  - bearerAuth: []