openapi: "3.0.3"
info:
  title: Payment Instrument API documentation
  description: <p>Payment Instrument and Cardholder operation management include APIs for Payment Instrument maintenance , Payment instrument operations and Status operation.</p>
  version: PowerCARD-Issuer 3.5.4-apiR5.3
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:
   # --- Cards/v2/{aliasPAN}/Renew
  /Cards/v2/{aliasPAN}/Renew:
        get:
            description:
                        <h3>API Overview</h3>
                          <p>
                               Usually a card is automatically renewed within the month it expires. However, for some reasons, as if when the customer is going to be out of the town during the renewal process, he may request to renew his card before its expiration date. For that, PowerCARD offers the possibility to use this web service. The service is mainly used to store the request that will be processed during the end of the day. 
                          </p>
                          <p>
                              It is important to mention here that PowerCARD makes multiple controls on the card before proceeding to perform the renewal action. Those controls are all defined in the system and can be activated or deactivated by the financial institution using the PowerCARD setup screens.
                          </p>
                        <h3>Functional Description</h3>
                         <img  src="./docs/RenewCard.png" />
            summary:    A customer can request to renew his card before its expiration date.
            tags:
              - Renew Card
            parameters:
              - in: path
                name: aliasPAN
                schema:
                  type: string
                required: true
                example: "4250120656063430"
                description: The AliasPAN value.
              - in: query
                name: cardNumber
                schema:
                  type: string
                description: The cardNumber value.
                example: "4250120656063430"
              - in: query
                name: requestUID
                schema:
                  type: string
                example: "6948DF80-14BD-4E04-8842-7668D9C001F5"
                description: Request Identifier. It is sent by the calling system as a universally unique identifier for the message. Used to match response with request messages.
              - in: query
                name: requestDate 
                schema:
                  type: string
                example: "2020-02-05T00:00:00"
                description: Date when the request was submitted.
              - in: query
                name: userID 
                schema:
                  type: string
                example: "001"
                description: Represents the user Id who made the request.
            responses:  
              200:
                description:
                        <div>
                                Successful
                                <p>Business Error Codes &#58;</p>
                                <table>
                                      <tr>
                                        <th>Error code</th>
                                        <th>Error Description</th>
                                      </tr>
                                      <tr> 
                                        <td>12701</td>
                                        <td>Invalid Card number</td>
                                      </tr>
                                      <tr> 
                                        <td>12702</td>
                                        <td>Invalid Card product</td>
                                      </tr>
                                      <tr> 
                                        <td>12703</td>
                                        <td>Operation not allowed</td>
                                      </tr>
                                      <tr> 
                                        <td>12704</td>
                                        <td>Operation not allowed for Cancelled card</td>
                                      </tr>
                                      <tr> 
                                        <td>12705</td>
                                        <td>Operation not allowed for Replaced card</td>
                                      </tr>
                                      <tr> 
                                        <td>12706</td>
                                        <td>Card blocked for renewal</td>
                                      </tr>
                                      <tr> 
                                        <td>12707</td>
                                        <td>Invalid Expiration date</td>
                                      </tr>
                                      <tr> 
                                        <td>12708</td>
                                        <td>The card is in production process, Contact your administrator</td>
                                      </tr>	
                                      <tr> 
                                        <td>12709</td>
                                        <td>Card is in the stop list, Contact your administrator</td>
                                      </tr>	
                                      <tr> 
                                        <td>12710</td>
                                        <td>The card is in Pin request process, Contact your administrator</td>
                                      </tr>							
                                      <tr> 
                                        <td>12711</td>
                                        <td>The card is in Replacement process</td>
                                      </tr>
                                      <tr> 
                                        <td>12712</td>
                                        <td>The card is in Renewal process</td>
                                      </tr>							
                                </table>
                        </div> 
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/RenewCardV35Rs'
                  application/xml:
                          schema:
                              $ref: '#/components/schemas/RenewCardV35Rs'    
 # Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>      
  schemas:
      RenewCardV35Rs:
                     $ref: 'response.yaml#/RenewCardV35Rs'         
security:
  - bearerAuth: []