openapi: "3.0.3"
info:
  title: Payment Instrument API documentation
  description: <p>Payment Instrument and Cardholder operation management include APIs for Payment Instrument maintenance , Payment instrument operations and Status operation.</p>
  version: PowerCARD-Issuer 3.5.4-apiR5.3
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:
  # --- Cards/v2/{aliasPAN}/Status
  /Cards/v2/{aliasPAN}/Status:
        patch:
            description:
                        <h3>API Overview</h3>
                          <p>
                              This web services was introduced to allow changing the status of an existing card in the system. Agent and customers can ask to change the status of a card by selecting a reason for that operation from a pre-defined list of reasons. It is important to note that the web service requires the card number and the desired operation as input. As output the web service send back the result of the processing that could be either successfully or unsuccessfully, in what case, the system will share an error code for investigation.
                          </p>
                        <h3>Functional Description</h3>
                         <img  src="./docs/UpdateCardStatus.png" />
            summary:    This web service allow changing the status of an existing card in the system.
            tags:
              - Update Card status
            parameters:
            - in: path
              name: aliasPAN
              schema:
                type: string
              required: true
              description: aliasPAN String value.
            requestBody:
              required: true
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/UpdateCardStatusV35Rq'
                application/xml:
                  schema:
                    $ref: '#/components/schemas/UpdateCardStatusV35Rq'
            responses:  
              200:
                description:
                      <div> Successful <p>Business Error Codes &#58;</p> <table>
                      <tr> <th>Error code</th> <th>Error Description</th> </tr>
                      <tr> <td>02001</td> <td>Card Does  not Exist</td> </tr>
                      <tr> <td>02002</td> <td>Wrong Card Number</td> </tr>
                      <tr> <td>02003</td> <td>Invalid Operation code</td> </tr>
                      <tr> <td>02004</td> <td>Card Expired</td> </tr>
                      <tr> <td>02005</td> <td>Invalid Range Date</td> </tr>
                      <tr> <td>02006</td> <td>Operation not permitted replaced card</td> </tr>
                      <tr> <td>02007</td> <td>Operation not permitted cancelled card</td> </tr>
                      <tr> <td>02008</td> <td>Operation not permitted  expired card</td> </tr>
                      <tr> <td>02009</td> <td>Card in the stop list</td> </tr>
                      <tr> <td>02010</td> <td>Invalid Reason Code</td></tr> </table>
                      </div>
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/UpdateCardStatusV35Rs'
                  application/xml:
                          schema:
                              $ref: '#/components/schemas/UpdateCardStatusV35Rs'     
 # Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>      
  schemas:
      UpdateCardStatusV35Rq:
                     $ref: 'request.yaml#/UpdateCardStatusV35Rq'
      UpdateCardStatusV35Rs:
                     $ref: 'response.yaml#/UpdateCardStatusV35Rs'         
security:
  - bearerAuth: []