openapi: "3.0.3"
info:
  title: Financial account API documentation
  description: <div><p>Financial account operation management include features for :Financial account, Account transactions and Statements list.</p>
  version: PowerCARD-Issuer V3.5
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:
  /UpdateFinancialAccountStatus/V2:
        post:
            description:
                        <h3>API Overview</h3>
                          <p>
                            The aim of this web service is to update the status of an existing Financial account, this web service can be invoked by customers and agents. The change will take place immediately in the system and all the next communication with that account will take the new status.</p>
                          <p>
                            As output the web service send back the result of the processing that could be either successfully or unsuccessfully, in what case, the system will share an error code and description for more details.                          </p>
                        <h3>Functional Description</h3>
                        <img  src="./docs/UpdateFinancialAccountStatus.png" />
            summary: The aim of this web service is to update the status of an existing Financial account...
            tags:
              - Update Financial Account Status
            requestBody:
              required: true
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/UpdateFinancialAccountStatusV35Rq'
                application/xml:
                  schema:
                    $ref: '#/components/schemas/UpdateFinancialAccountStatusV35Rq'
            responses:  
              200:
                description:
                        <div>
                                Successful
                                <p>Business Error Codes &#58;</p>
                                <table>
                                      <tr>
                                        <th>Error code</th>
                                        <th>Error Description</th>
                                      </tr>
                                      <tr> 
                                        <td>13301</td>
                                        <td>INVALID ACCOUNT ID</td>
                                      </tr>
                                       <tr> 
                                        <td>13302</td>
                                        <td>INVALID ACCOUNT STATUS</td>
                                      </tr>
                                      <tr> 
                                        <td>13303</td>
                                        <td>INVALID ACCOUNT ST RS</td>
                                      </tr>   
                                      <tr> 
                                        <td>13304</td>
                                        <td>INVALID TRANSITION RQ</td>
                                      </tr>                                        
                                </table>
                        </div> 
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/UpdateFinancialAccountStatusV35Rs' 
                  application/xml:
                          schema:
                            $ref: '#/components/schemas/UpdateFinancialAccountStatusV35Rs'
 # Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>      
  schemas:
    # --- Import UpdateFinancialAccountStatus request and response
      UpdateFinancialAccountStatusV35Rq:
               $ref: 'request.yaml#/UpdateFinancialAccountStatusV35Rq'
      UpdateFinancialAccountStatusV35Rs:
               $ref: 'response.yaml#/UpdateFinancialAccountStatusV35Rs'
security:
  - bearerAuth: []