openapi: "3.0.3"
info:
  title: Financial account API documentation
  description: <div><p>Financial account operation management include features for :Financial account, Account transactions and Statements list.</p>
  version: PowerCARD-Issuer V3.5
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:
  #updateAccStatementCode    
  /UpdateAccStatementCode/V2:
        post:
            description:
                        <h3>API Overview</h3>
                          <p>
                           Users may request to change their statement specification by changing for instance the type of statement being received. Meantime the financial institution may request to change some other parameters on the customer statement moving the customer from a category to another one with different statement requirements. To do that PowerCARD offers this web service that only by providing the account number as well as the statement code can adjust that in the PowerCARD database hence all the statements generated will follow the characteristics of the statement code
                          </p>
                        <h3>Functional Description</h3>
                        <img  src="./docs/updateAccStatementCode.png" />
            summary: Change statement specification by changing for instance the type of statement...
            tags:
              - Update Account Statement Code
            requestBody:
              required: true
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/UpdateAccStatementCodeV35Rq'
                application/xml:
                  schema:
                    $ref: '#/components/schemas/UpdateAccStatementCodeV35Rq'
            responses:  
              200:
                description:
                        <div>
                                Successful
                                <p>Business Error Codes &#58;</p>
                                <table>
                                      <tr>
                                        <th>Error code</th>
                                        <th>Error Description</th>
                                      </tr>
                                      <tr>
                                         <td>17301</td>
                                         <td>Invalid Account number</td>
                                      </tr>
                                      <tr>
                                         <td>17302</td>
                                         <td>Invalid Statement Code</td>
                                      </tr>
                                </table>
                        </div> 
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/UpdateAccStatementCodeV35Rs'
                  application/xml:
                          schema:
                            $ref: '#/components/schemas/UpdateAccStatementCodeV35Rs'                
 # Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>      
  schemas:
      UpdateAccStatementCodeV35Rq:
               $ref: 'request.yaml#/UpdateAccStatementCodeV35Rq'
      UpdateAccStatementCodeV35Rs:
               $ref: 'response.yaml#/UpdateAccStatementCodeV35Rs'   
security:
  - bearerAuth: []