openapi: "3.0.3"
info:
  title: Customer Management API documentation
  description: <p>PowerCARD Connect’API offers through APIs specific functions that group in a functional logic, all features relating to Client operations management. </p>
  version: PowerCARD-Issuer V4
servers:
  - url: https://api.wemeeting2023.pwcv4.com
    description: Development server
paths:
  /customer-management/v4.0/customers/update_event_notification:
    patch:
      deprecated: true
      description:
        <h3>API Overview</h3>
        <p>
          This web service is used activate/deactivate a communication event/channel as well as set communication event channel preferences.
          The following sections are intended to highlight the process as well as the technical specification of the request and response messages.        
        </p>
        <h3>Functional Description</h3>
        <img  src="./docs/updateEventNotification.png" />
      summary: Update client event notification
      tags:
        - Update event notification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateEventNotificationV4Rq'
          application/xml:
            schema:
              $ref: '#/components/schemas/UpdateEventNotificationV4Rq'
      responses:
        200:
          description:
            <div>
            <p>Technical Error Codes &#58;</p>
            <table>
            <tr>
            <th>Error code</th>
            <th>Error Description</th>
            </tr>
            <tr>
            <td>00000</td>
            <td>Success</td>
            </tr>
            <tr>
            <td>99999</td>
            <td>System error</td>
            </tr>
            <tr>
            <td>90009</td>
            <td>Generic error for request validation (check size,format,mandatory etc..)</td>
            </tr>
            <tr>
            <td>00002</td>
            <td> Forbidden you don't have permission to access for this api</td>
            </tr>
            <tr>
            <td>00007</td>
            <td>Authorization header is empty</td>
            </tr>
            <tr>
            <td>00008</td>
            <td>Authorization header is missing</td>
            </tr>
            <tr>
            <td>00009</td>
            <td>Malformat Authorization content</td>
            </tr>
            <tr>
            <td>00010</td>
            <td>Bearer is required in the token</td>
            </tr>
            <tr>
            <td>00011</td>
            <td>Token expired</td>
            </tr>
            <tr>
            <td>00012</td>
            <td>Invalid token</td>
            </tr>
            <tr>
            <td>00014</td>
            <td>Invalid business date</td>
            </tr>
            </table>
            <p>Business Error Codes &#58;</p>
            <table>
            <tr>
            <th>Error code</th>
            <th>Error Description</th>
            </tr>
            <tr>
            <td>000099</td>
            <td>Invalid Customer Id</td>
            </tr>
            <tr>
            <td>000174</td>
            <td>strategyId is required</td>
            </tr>
            </table>
            </div>
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateEventNotificationV4Rs'
            application/xml:
              schema:
                $ref: '#/components/schemas/UpdateEventNotificationV4Rs'
# Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description:
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>
  schemas:
      UpdateEventNotificationV4Rq:
               $ref: 'request.yaml#/UpdateEventNotificationV4Rq'
      UpdateEventNotificationV4Rs:
               $ref: 'response.yaml#/UpdateEventNotificationV4Rs'
security:
  - bearerAuth: []
