openapi: "3.0.3"
info:
  title: PowerCARD-Switch API documentation
  description: PowerCARD-Switch offers 100% availability with active/ active architecture, it is also able to process thousands of transactions per second. A performance expected in the mission-critical world of electronic payment transaction processing.
  version: PowerCARD 3.5.4-apiR5.3 
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths: 
  #Cards/v2/{aliasPAN}/CVC2
  /Cards/v2/{aliasPAN}/CVC2:
        get:
            description:
                        <h3>API Overview</h3>
                          <p>
                               This web service is mainly used to retrieve the CVC2  when providing a PAN or PAN Alias. PowerCARD is in fact a tokenization system that accepts as entry token value and proceeds by the reverse process of redeeming a token for its associated PAN value.
                          </p>
                          <p>
                               The following sections are intended to highlight the process as well as the technical specification of the request and response messages.  
                          </p>
                        <h3>Functional Description</h3>
                        <img  src="./docs/GetCardCVC2.png" />
            summary: This web service is mainly used to retrieve the CVC2  when providing a PAN or PAN Alias.
            tags:
              - Get Card CVC2.
            parameters:
              - in: path
                name: aliasPAN
                schema:
                  type: string
                required: true
                description: AliasPAN String to get card details.
              - in: query
                name: requestUID 
                schema:
                  type: string
                description: Request Identifier. It is sent by the calling system as a universally unique identifier for the message. Used to match response with request messages.
              - in: query
                name: requestDate 
                schema:
                  type: string
                description: Date when the request was submitted.
              - in: query
                name: userID 
                schema:
                  type: string
                description: Represents the user Id who made the request.
            responses:  
              200:
                description:
                        <div>
                                Successful
                                <p>Business Error Codes &#58;</p>
                                <table>
                                    <tr>
                                      <th>Error code</th>
                                      <th>Error Description</th>
                                    </tr>
                                    <tr> 
                                      <td>20901</td>
                                      <td>Invalid Card Number/Token Id</td>
                                    </tr>								
                                </table>
                        </div> 
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/GetCardCVC2V35Rs'
                  application/xml:
                      schema:
                          $ref: '#/components/schemas/GetCardCVC2V35Rs'   
# Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>      
  schemas:
    # --- Import GetCardCVC2V35 request and response definition
      GetCardCVC2V35Rq:
            $ref: 'request.yaml#/GetCardCVC2V35Rq'
      GetCardCVC2V35Rs:
            $ref: 'response.yaml#/GetCardCVC2V35Rs'
  security:
  - bearerAuth: []
