openapi: "3.0.3"
info:
  title: Payment Instrument API documentation
  description: <p>Payment Instrument and Cardholder operation management include APIs for Payment Instrument maintenance , Payment instrument operations and Status operation.</p>
  version: PowerCARD-Issuer 3.5.4-apiR5.3
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:

  # --- /GenerateMerchantQRCode/V3
  /GenerateMerchantQRCode/V3:
    post:
      description:
        <h3>API Overview</h3>
        <p>
        The present web service is aimed to be used whenever any user would like to  generate Merchant QR Code for payments based on EMVco specifications, this API return a TLV value (representing the generated QRCode) for each acceptor point belonging to specified site or merchant depending on values defined on request. The generated QR code respects the EMVCo Merchant Presented QR specifications.
        </p>
        <h3>Functional Description</h3>
        <img  src="./docs/GenerateMerchantQRCode.png" />
      summary:   A debit card allows the cardholder access to a source of funding that is linked to his/her card.
      tags:
        - Generate Merchant QRCode
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateMerchantQRCodeRq'
          application/xml:
            schema:
              $ref: '#/components/schemas/GenerateMerchantQRCodeRq'
      responses:
        200:
          description:
            <div>
            Successful
            <p>Business Error Codes &#58;</p>
            <table>
            <tr>
            <th>Error Code</th>
            <th>Description</th>
            </tr>
            <tr><td>61600</td><td>Invalid Merchant Bank Code</td></tr>
            <tr><td>61601</td><td>Invalid Merchant ID</td></tr>
            <tr><td>61602</td><td>Invalid Site Id</td></tr>
            <tr><td>61603</td><td>Invalid Acceptor Point Id</td></tr>
            <tr><td>61604</td><td>Invalid TerminalId</td></tr>
            <tr><td>61605</td><td>Invalid QRCode Template</td></tr>
            <tr><td>61606</td><td>Invalid QRCode Version</td></tr>
            <tr><td>61607</td><td>Invalid QRCode Format</td></tr>
            <tr><td>61608</td><td>Invalid QRCode Type</td></tr>
            <tr><td>61609</td><td>Invalid QrCode Amount</td></tr>
            <tr><td>61610</td><td>Error has occurred while QRCode generation</td></tr>
            
            </table>
            </div>
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenerateMerchantQRCodeRs'
            application/xml:
              schema:
                $ref: '#/components/schemas/GenerateMerchantQRCodeRs'
  # Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description:
        <div>
        <h5>Api key authorization</h5>
        <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
        <table>
        <tr>
        <td>Name &#8282;</td>
        <td>Authorization</td>
        </tr>
        <tr>
        <td>In &#8282;</td>
        <td>Header</td>
        </tr>
        </table>
        </div>
  schemas:

    # --- Import GenerateMerchantQRCode request and response
    GenerateMerchantQRCodeRq:
      $ref: 'request.yaml#/GenerateMerchantQRCodeRq'
    GenerateMerchantQRCodeRs:
      $ref: 'response.yaml#/GenerateMerchantQRCodeRs'
security:
  - bearerAuth: []