openapi: "3.0.3"
info:
  title: Payment Instrument API documentation
  description: <p>Payment Instrument and Cardholder operation management include APIs for Payment Instrument maintenance , Payment instrument operations and Status operation.</p>
  version: PowerCARD-Issuer 3.5.4-apiR5.3
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:

  # --- /GetMerchantBatchDetails/V3
  /GetMerchantBatchDetails/V3:
    post:
      description:
        <h3>API Overview</h3>
        <p>
        The present web service is aimed to be used whenever any user would like to retrieve details regarding a given batch/remittance. Each batch is identified in the system by an internal identification and should contain a list of transactions.
        </p>
        <h3>Functional Description</h3>
        <img  src="./docs/GetMerchantBatchDetails.png" />
      summary:   A debit card allows the cardholder access to a source of funding that is linked to his/her card.
      tags:
        - Search Merchant Batches
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetMerchantBatchDetailsRq'
          application/xml:
            schema:
              $ref: '#/components/schemas/GetMerchantBatchDetailsRq'
      responses:
        200:
          description:
            <div>
            Successful
            <p>Business Error Codes &#58;</p>
            <table>
            <tr>
            <th>Error Code</th>
            <th>Description</th>
            </tr>
            <tr><td>60100</td><td>Invalid Merchant Bank Code</td></tr>
            <tr><td>60136</td><td>You should specify at least one on this fields:<b> Merchant ID or legal ID</b></td></tr>
            <tr><td>60200</td><td>Merchant not found</td></tr>
            <tr><td>61401</td><td>No batch found with requested filters</td></tr>
            
            </table>
            </div>
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMerchantBatchDetailsRs'
            application/xml:
              schema:
                $ref: '#/components/schemas/GetMerchantBatchDetailsRs'
  # Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description:
        <div>
        <h5>Api key authorization</h5>
        <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
        <table>
        <tr>
        <td>Name &#8282;</td>
        <td>Authorization</td>
        </tr>
        <tr>
        <td>In &#8282;</td>
        <td>Header</td>
        </tr>
        </table>
        </div>
  schemas:

    # --- Import GetMerchantBatchDetailsRq request and response
    GetMerchantBatchDetailsRq:
      $ref: 'request.yaml#/GetMerchantBatchDetailsRq'
    GetMerchantBatchDetailsRs:
      $ref: 'response.yaml#/GetMerchantBatchDetailsRs'
security:
  - bearerAuth: []