openapi: "3.0.3"
info:
  title: Payment Instrument API documentation
  description: <p>Payment Instrument and Cardholder operation management include APIs for Payment Instrument maintenance , Payment instrument operations and Status operation.</p>
  version: PowerCARD-Issuer 3.5.4-apiR5.3
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:

  # --- /SearchMerchantTransactions/V3
  /SearchMerchantTransactions/V3:
    post:
      description:
        <h3>API Overview</h3>
        <p>
        The current web service is used to search and retrieve transaction data for an acquiring entity in the system. An acquiring entity may include a VAR, a Chain; a Merchant or a point of sale. Both agent and merchants representatives may use different criteria to search and display transactions posted to the merchant account. Criteria could include amount ranges, dates, Account id, transaction types, network…More details regarding the list of criteria is shared bellow.
        </p>
        <h3>Functional Description</h3>
        <img  src="./docs/SearchMerchantTransactions.png" />
      summary:   A debit card allows the cardholder access to a source of funding that is linked to his/her card.
      tags:
        - Search Merchant Transactions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MerTransSettlementRq'
          application/xml:
            schema:
              $ref: '#/components/schemas/MerTransSettlementRq'
      responses:
        200:
          description:
            <div>
            Successful
            <p>Business Error Codes &#58;</p>
            <table>
            <tr>
            <th>Error Code</th>
            <th>Description</th>
            </tr>
            <tr><td>60100</td><td>Invalid Merchant Bank Code</td></tr>
            <tr><td>60136</td><td>You should specify at least one on this fields:<b> Merchant ID or legal ID</td></tr>
            <tr><td>60200</td><td>Merchant not found</td></tr>
            <tr><td>60900</td><td>Invalid Acceptor Point ID</td></tr>
            <tr><td>60901</td><td>Invalid Transaction Code</td></tr>
            <tr><td>60903</td><td>Invalid Settlement Date</td></tr>
            <tr><td>60904</td><td>Invalid Transaction Date</td></tr>
            <tr><td>60905</td><td>Invalid Settlement status</td></tr>
            
            </table>
            </div>
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MerTransSettlementRs'
            application/xml:
              schema:
                $ref: '#/components/schemas/MerTransSettlementRs'
  # Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description:
        <div>
        <h5>Api key authorization</h5>
        <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
        <table>
        <tr>
        <td>Name &#8282;</td>
        <td>Authorization</td>
        </tr>
        <tr>
        <td>In &#8282;</td>
        <td>Header</td>
        </tr>
        </table>
        </div>
  schemas:

    # --- Import MerTransSettlementRq request and response
    MerTransSettlementRq:
      $ref: 'request.yaml#/MerTransSettlementRq'
    MerTransSettlementRs:
      $ref: 'response.yaml#/MerTransSettlementRs'
security:
  - bearerAuth: []