openapi: "3.0.3"
info:
  title: PowerCARD-Acquirer API documentation
  description: This reference lists the new, enhanced, and removed features, resolved and known issues, documentation notes, and documentation updates in this release 4.2 of Connect’API.
  version: PowerCARD 3.2-apiR4.2
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:
  # ------- closeCase
  /CloseCase/V1:
    post:
      description:  <h3>API Overview</h3>
                    <p>PowerCARD offers a comprehensive case management module that enables users to create and maintain cases in the system. It helps also to make the follow up of any case created as well as performing some actions on it.</p>
                    <p>The present web service aims to close a case of an existing case in the system. The message requires the case reference Identification subject to that closure. If not present, the request will be rejected, and a specific error code will be returned.</p>
                    <h3>Functional Description</h3>
                   <img  src="./docs/closeCase.png" />
                  
      summary: PowerCARD offers a comprehensive case management module that enables users...
      tags:
        - Close Case
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CloseCaseRq'
          application/xml:
            schema:
              $ref: '#/components/schemas/CloseCaseRq'
      responses:  
         200:
          description:
                  <div>
                          Successful
                          <p>Business Error Codes &#58;</p>
                           <table>
                                <tr>
                                  <th>Error code</th>
                                  <th>Error Description</th>
                                </tr>
                                <tr> 
                                  <td>00551</td>
                                  <td>Case reference not provided in the request message</td>
                                </tr>	
                                <tr> 
                                  <td>00552</td>
                                  <td>Case reference not found in the system</td>
                                </tr>	
                                <tr> 
                                  <td>00553</td>
                                  <td>Case already closed</td>
                                </tr>									
                           </table>
                  </div> 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CloseCaseRs'                                                                                                  
# Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>      
  schemas:
    # --- Import CloseCase request and response 
      CloseCaseRq:
               $ref: 'request.yaml#/CloseCaseRq'
      CloseCaseRs:
               $ref: 'response.yaml#/CloseCaseRs'                                                                                      
security:
  - bearerAuth: []



