openapi: "3.0.3"
info:
  title: PowerCARD-Acquirer API documentation
  description: This reference lists the new, enhanced, and removed features, resolved and known issues, documentation notes, and documentation updates in this release 4.2 of Connect’API.
  version: PowerCARD 3.2-apiR4.2
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:
  # ------- getMerchantContractDetail
  /GetMerchantContractDetail/V1:
    post:
      description:  <h3>API Overview</h3>
                    <p>The aim of this Web service is to retrieve data related to a given merchant contract as defined under the PowerCARD merchant management system. Details are stored in multiple PowerCARD tables, they are all processed then returned back in the response message.</p>
                    <h3>Functional Description</h3>
                    <img  src="./docs/GetMerchantContractDetail.jpg" />
                  
      summary: The aim of this Web service is to retrieve data related to a given merchant..
      tags:
        - Get Merchant Contract Detail
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetMerchantContractDetailRq'
          application/xml:
            schema:
              $ref: '#/components/schemas/GetMerchantContractDetailRq'
      responses:  
         200:
          description: 
                <div>
                          Successful
                          <p>Business Error Codes &#58;</p>
                           <table>
                                <tr>
                                  <th>Error code</th>
                                  <th>Error Description</th>
                                </tr>
                                <tr> 
                                  <td>10801</td>
                                  <td>Invalid merchant number</td>
                                </tr>	
                                <tr> 
                                  <td>10802</td>
                                  <td>Invalid contract id</td>
                                </tr>										
                           </table>
                  </div> 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMerchantContractDetailRs'
            application/xml:
              schema:
                $ref: '#/components/schemas/GetMerchantContractDetailRs'                                                                                          
# Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>      
  schemas:
    # --- Import DemoV35 request and response
      GetMerchantContractDetailRq:
               $ref: 'request.yaml#/GetMerchantContractDetailRq'
      GetMerchantContractDetailRs:
               $ref: 'response.yaml#/GetMerchantContractDetailRs'                                                                                      
security:
  - bearerAuth: []



