openapi: "3.0.3"
info:
  title: PowerCARD-Acquirer API documentation
  description: This reference lists the new, enhanced, and removed features, resolved and known issues, documentation notes, and documentation updates in this release 4.2 of Connect’API.
  version: PowerCARD 3.2-apiR4.2
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:
  # ------- getMerchantDetail
  /GetMerchantDetail/V1:
    post:
      description:  <h3>API Overview</h3>
                    <p>The current web service is used to allow agents as well as merchants to get more details about an existing merchant in the merchant database.</p>
                    <p>Merchant details can include Merchant category code (MCC), Merchant activities, Merchant sites, bank accounts, equipment’s, contacts info, subscribed services….
                    This Web Service can be called by a Merchant or an Agent.
                    </p>
                    <h3>Functional Description</h3>
                    <img  src="./docs/getMerchantDetail.png" />
                  
      summary: The current web service is used to allow agents as well as merchants...
      tags:
        - Get Merchant Detail
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetMerchantDetailRq'
          application/xml:
            schema:
              $ref: '#/components/schemas/GetMerchantDetailRq'
      responses:  
         200:
          description:
                  <div>
                          Successful
                          <p>Business Error Codes &#58;</p>
                           <table>
                                <tr>
                                  <th>Error code</th>
                                  <th>Error Description</th>
                                </tr>
                                <tr> 
                                  <td>06701</td>
                                  <td>Merchant required</td>
                                </tr>	
                                <tr> 
                                  <td>06702</td>
                                  <td>The merchant ID is invalid</td>
                                </tr>										
                           </table>
                  </div> 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMerchantDetailRs'
            application/xml:
               schema:
                  $ref: '#/components/schemas/GetMerchantDetailRs'                                                                                      
# Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>      
  schemas:
    # --- Import GetMerchantDetail request and response 
      GetMerchantDetailRq:
               $ref: 'request.yaml#/GetMerchantDetailRq' 
      GetMerchantDetailRs:
               $ref: 'response.yaml#/GetMerchantDetailRs'                                                                                       
security:
  - bearerAuth: []



