openapi: "3.0.3"
info:
  title: PowerCARD-Acquirer API documentation
  description: This reference lists the new, enhanced, and removed features, resolved and known issues, documentation notes, and documentation updates in this release 4.2 of Connect’API.
  version: PowerCARD 3.2-apiR4.2
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:
  # ------- getOutletDetails
  /GetOutletDetails/V1:
    post:
      description:  <h3>API Overview</h3>
                    <p>If any user is looking for information with regards to a point of sale (Outlet), he needs to use the current web service. The user is required to specify in the request message the point of sale identification number as defined internally in PowerCARD and as a result he will expect to receive a record containing all the information related to that point of sale. Information may include important demographic data for that point of sale, legal information, address, list of contacts, contracts…</p>
                    <h3>Functional Description</h3>
                    <img  src="./docs/getOutletDetails.png" />
                  
      summary: If any user is looking for information with regards to a point of sale (Outlet)...
      tags:
        - Get Outlet Details
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetOutletDetailsRq'
          application/xml:
            schema:
              $ref: '#/components/schemas/GetOutletDetailsRq'
      responses:  
         200:
          description:
                  <div>
                          Successful
                          <p>Business Error Codes &#58;</p>
                           <table>
                                <tr>
                                  <th>Error code</th>
                                  <th>Error Description</th>
                                </tr>
                                <tr> 
                                  <td>06801</td>
                                  <td>Point of sale Identification not provided</td>
                                </tr>	
                                <tr> 
                                  <td>06802</td>
                                  <td>Invalid Point of sale Identification</td>
                                </tr>										
                           </table>
                  </div> 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetOutletDetailsRs'                                                                                           
# Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>      
  schemas:
    # --- Import GetOutletDetails request and response 
      GetOutletDetailsRq:
               $ref: 'request.yaml#/GetOutletDetailsRq'
      GetOutletDetailsRs:
               $ref: 'response.yaml#/GetOutletDetailsRs'                                                                                          
security:
  - bearerAuth: []



