openapi: "3.0.3"
info:
  title: PowerCARD-Acquirer API documentation
  description: This reference lists the new, enhanced, and removed features, resolved and known issues, documentation notes, and documentation updates in this release 4.2 of Connect’API.
  version: PowerCARD 3.2-apiR4.2
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:
  # ------- updateMerchantActivityStatus
  /UpdateMerchantActivityStatus/V1:
    post:
      description:  <h3>API Overview</h3>
                    <p>PowerCARD offers a comprehensive merchant management module that enables users to create and maintain merchants in the system. For instance, this web service helps users to update a merchant activity status. By doing so, users might for example cancel a given merchant activity.</p>
                    <h3>Functional Description</h3>
                    <img  src="./docs/updateMerchantActivityStatus.png" />
                  
      summary: PowerCARD offers a comprehensive merchant management module that enables users to create and maintain merchants in the system.
      tags:
        - Update Merchant Activity Status
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateMerchantActivityStatusRq'
          application/xml:
            schema:
              $ref: '#/components/schemas/updateMerchantActivityStatusRq'
      responses:  
         200:
          description:
                  <div>
                          Successful
                          <p>Business Error Codes &#58;</p>
                           <table>
                                <tr>
                                  <th>Error code</th>
                                  <th>Error Description</th>
                                </tr>
                                <tr> 
                                  <td>06901</td>
                                  <td>Invalid merchant </td>
                                </tr>
                                <tr> 
                                  <td>06902</td>
                                  <td>Update not allowed for this merchant, merchant should have one of the following statuses N Normal, S Suspended, M Under Monitoring</td>
                                </tr>
                                <tr> 
                                  <td>06903</td>
                                  <td>Update not allowed for this merchant, merchant should have one of the following statuses N Normal, S Suspended, M Under Monitoring </td>
                                </tr>	
                                <tr> 
                                  <td>06904</td>
                                  <td>Update not allowed for this merchant, merchant should have one of the following statuses N Normal, S Suspended, M Under Monitoring</td>
                                </tr>	
                                <tr> 
                                  <td>06905</td>
                                  <td>Activity is not secondary </td>
                                </tr>	
                                <tr> 
                                  <td>06906</td>
                                  <td>Error while updating activity status </td>
                                </tr>	
                                <tr> 
                                  <td>06907</td>
                                  <td>Invalid status code and reason code </td>
                                </tr>									
                           </table>
                  </div> 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/updateMerchantActivityStatusRs'                                                                                            
# Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>      
  schemas:

    # --- Import updateMerchantActivityStatus request and response 
      updateMerchantActivityStatusRq:
               $ref: 'request.yaml#/updateMerchantActivityStatusRq'
      updateMerchantActivityStatusRs:
               $ref: 'response.yaml#/updateMerchantActivityStatusRs'                                                                                     
security:
  - bearerAuth: []



