openapi: "3.0.3"
info:
  title: PowerCARD-Acquirer API documentation
  description: This reference lists the new, enhanced, and removed features, resolved and known issues, documentation notes, and documentation updates in this release 4.2 of Connect’API.
  version: PowerCARD 3.2-apiR4.2
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:
  # ------- updateMerchantActivity
  /UpdateMerchantActivity/V1:
    post:
      description:  <h3>API Overview</h3>
                    <p>A merchant activity is that which is performed by persons participating in the market to provide goods or services with a monetary value for the purpose of obtaining profit or earnings. This web service is intended to help any user to amend the details of activities of any predefined merchant in the PowerCARD Acquirer database by just providing the merchant activity identification.</p>
                    <h3>Functional Description</h3>
                    <img  src="./docs/updateMerchantActivity.png" />
                  
      summary: A merchant activity is that which is performed by persons participating in the market...
      tags:
        - Update Merchant Activity
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateMerchantActivityRq'
          application/xml:
            schema:
              $ref: '#/components/schemas/updateMerchantActivityRq'
      responses:  
         200:
          description:
                  <div>
                          Successful
                          <p>Business Error Codes &#58;</p>
                           <table>
                              <tr>
                                <th>Error code</th>
                                <th>Error Description</th>
                              </tr>
                              <tr> 
                                <td>08201</td>
                                <td>Activity Identifier not found</td>
                              </tr>
                              <tr> 
                                <td>08202</td>
                                <td>MCC not found</td>
                              </tr>
                              <tr> 
                                <td>08203</td>
                                <td>MCC already linked to that merchant</td>
                              </tr>	
                              <tr> 
                                <td>08204</td>
                                <td>Merchant not found</td>
                              </tr>	
                              <tr> 
                                <td>08205</td>
                                <td>Update not allowed for this account, it's closed </td>
                              </tr>									
                           </table>
                  </div> 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/updateMerchantActivityRs'                                                                                           
# Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>      
  schemas:
    # --- Import updateMerchantActivity request and response 
      updateMerchantActivityRq:
               $ref: 'request.yaml#/updateMerchantActivityRq' 
      updateMerchantActivityRs:
               $ref: 'response.yaml#/updateMerchantActivityRs'                                                                                       
security:
  - bearerAuth: []



