openapi: "3.0.3"
info:
  title: PowerCARD-Acquirer API documentation
  description: This reference lists the new, enhanced, and removed features, resolved and known issues, documentation notes, and documentation updates in this release 4.2 of Connect’API.
  version: PowerCARD 3.2-apiR4.2
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:
  # ------- updateMerchantContract
  /UpdateMerchantContract/V1:
    post:
      description:  <h3>API Overview</h3>
                    <p>The present web service is aimed to be used whenever any user would like to change a detail of a contract in the system. Whenever it is requested to do, users need to provide information with regards to the contract details so that PowerCARD can proceed and change accordingly.</p>
                    <h3>Functional Description</h3>
                    <img  src="./docs/updateMerchantContract.png" />
                  
      summary: The present web service is aimed to Change a detail of a contract...
      tags:
        - Update Merchant Contract
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateMerchantContractRq'
          application/xml:
            schema:
              $ref: '#/components/schemas/UpdateMerchantContractRq'
      responses:  
         200:
          description:
                  <div>
                          Successful
                          <p>Business Error Codes &#58;</p>
                           <table>
                                <tr>
                                  <th>Error code</th>
                                  <th>Error Description</th>
                                </tr>
                                <tr> 
                                  <td>00971</td>
                                  <td>Invalid bank code</td>
                                </tr>
                                <tr> 
                                  <td>00972</td>
                                  <td>Invalid branch code</td>
                                </tr>
                                <tr> 
                                  <td>00973</td>
                                  <td>Invalid contract element id</td>
                                </tr>	
                                <tr> 
                                  <td>00974</td>
                                  <td>Contract element id already exists</td>
                                </tr>	
                                <tr> 
                                  <td>00975</td>
                                  <td>Invalid product code</td>
                                </tr>	
                                <tr> 
                                  <td>00976</td>
                                  <td>Product code is mandatory</td>
                                </tr>
                                <tr> 
                                  <td>00977</td>
                                  <td>Invalid product code and contract element id</td>
                                </tr>	
                                <tr> 
                                  <td>00978</td>
                                  <td>Error while checking characteristic list  </td>
                                </tr>	
                                <tr> 
                                  <td>00979</td>
                                  <td>Error while checking service option list</td>
                                </tr>	
                                <tr> 
                                  <td>00980</td>
                                  <td>Invalid charging id</td>
                                </tr>	
                                <tr> 
                                  <td>00981</td>
                                  <td>Charging id is mandatory</td>
                                </tr>	
                                <tr> 
                                  <td>00982</td>
                                  <td>Error while checking charging condition list</td>
                                </tr>
                                <tr> 
                                  <td>00983</td>
                                  <td>Error while checking settlement condition list</td>
                                </tr>	
                                <tr> 
                                  <td>00984</td>
                                  <td>Invalid product context code</td>
                                </tr>	
                                <tr> 
                                  <td>00985</td>
                                  <td>Invalid posting id</td>
                                </tr>	
                                <tr> 
                                  <td>00986</td>
                                  <td>Invalid context value</td>
                                </tr>
                                <tr> 
                                  <td>00987</td>
                                  <td>Invalid merchant number</td>
                                </tr>								
                           </table>
                  </div> 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateMerchantContractRs'                                                                                           
# Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>      
  schemas:
    # --- Import UpdateMerchantContract request and response 
      UpdateMerchantContractRq:
               $ref: 'request.yaml#/UpdateMerchantContractRq' 
      UpdateMerchantContractRs:
               $ref: 'response.yaml#/UpdateMerchantContractRs'                                                                                         
security:
  - bearerAuth: []



