openapi: "3.0.3"
info:
  title: PowerCARD-Acquirer API documentation
  description: This reference lists the new, enhanced, and removed features, resolved and known issues, documentation notes, and documentation updates in this release 4.2 of Connect’API.
  version: PowerCARD 3.2-apiR4.2
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:
  # ------- updateMerchantContactDetails
  /UpdateMerchantContactDetails/V1:
    post:
      description:  <h3>API Overview</h3>
                    <p>The present web service is aimed to be used whenever any user would like to change a detail of a merchant contact details in the system. Whenever it is requested to do, users need to provide information with regards to the merchant contact details so that PowerCARD can proceed and change accordingly.</p>
                    <h3>Functional Description</h3>
                     <img  src="./docs/updateMerchantContactDetails.png" />
                  
      summary: Used whenever any user would like to change a detail of a merchant contact...
      tags:
        - Update Merchant Contact Details
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateMerchantContactDetailsRq'
          application/xml:
            schema:
              $ref: '#/components/schemas/UpdateMerchantContactDetailsRq'
      responses:  
         200:
          description:
                  <div>
                          Successful
                          <p>Business Error Codes &#58;</p>
                           <table>
                                <tr>
                                  <th>Error code</th>
                                  <th>Error Description</th>
                                </tr>
                                <tr> 
                                  <td>08701</td>
                                  <td>Invalid language code</td>
                                </tr>
                                <tr> 
                                  <td>08702</td>
                                  <td>Invalid document code</td>
                                </tr>
                                <tr> 
                                  <td>08703</td>
                                  <td>Invalid Country code</td>
                                </tr>	
                                <tr> 
                                  <td>08704</td>
                                  <td>Invalid merchant number</td>
                                </tr>	
                                <tr> 
                                  <td>08705</td>
                                  <td>Invalid merchant representative Identification</td>
                                </tr>	
                                <tr> 
                                  <td>08706</td>
                                  <td>Address list identification not found</td>
                                </tr>
                                <tr> 
                                  <td>08707</td>
                                  <td>Address detail not defined</td>
                                </tr>	
                                <tr> 
                                  <td>08708</td>
                                  <td>First name is null</td>
                                </tr>	
                                <tr> 
                                  <td>08709</td>
                                  <td>Last name is null</td>
                                </tr>	
                                <tr> 
                                  <td>08710</td>
                                  <td>Invalid title code</td>
                                </tr>	
                                <tr> 
                                  <td>08711</td>
                                  <td>Invalid representative position</td>
                                </tr>	
                                <tr> 
                                  <td>08712</td>
                                  <td>The values provided in Country, region, city and postal code are not coherent</td>
                                </tr>
                                <tr> 
                                  <td>08713</td>
                                  <td>The values provided in Country, region and city are not coherent</td>
                                </tr>	
                                <tr> 
                                  <td>08714</td>
                                  <td>Invalid Address type </td>
                                </tr>	
                                <tr> 
                                  <td>08715</td>
                                  <td>Phone type not found</td>
                                </tr>	
                                <tr> 
                                  <td>08716</td>
                                  <td>Invalid City code</td>
                                </tr>	
                                <tr> 
                                  <td>08717</td>
                                  <td>Update not allowed for this merchant, merchant should have one of the following statuses N Normal, S Suspended, M Under Monitoring</td>
                                </tr>									
                           </table>
                  </div> 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/demoV35Rs'                                                                                          
# Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>      
  schemas:
    # --- Import UpdateMerchantContactDetails request and response 
      UpdateMerchantContactDetailsRq:
               $ref: 'request.yaml#/UpdateMerchantContactDetailsRq'
      demoV35Rs:
               $ref: 'response.yaml#/DemoV35Rs'  
    # --- Import DemoV35 request and response                                                                                      
security:
  - bearerAuth: []



