openapi: "3.0.3"
info:
  title: PowerCARD-Acquirer API documentation
  description: This reference lists the new, enhanced, and removed features, resolved and known issues, documentation notes, and documentation updates in this release 4.2 of Connect’API.
  version: PowerCARD 3.2-apiR4.2
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:
  # ------- updateMerchantBankAccount
  /UpdateMerchantBankAccount/V1:
    post:
      description:  <h3>API Overview</h3>
                    <p>The present web service is aimed to be used whenever any user would like to change a detail of a merchant bank account information in the system. Whenever it is requested to do, users need to provide information with regards to the merchant account number, status… so that PowerCARD can proceed and change accordingly.</p>
                    <h3>Functional Description</h3>
                    <img  src="./docs/updateMerchantBankAccount.png" />
                  
      summary: Used whenever any user would like to change merchant bank account information ...
      tags:
        - Update Merchant Bank Account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateMerchantBankAccountRq'
          application/xml:
            schema:
              $ref: '#/components/schemas/UpdateMerchantBankAccountRq'
      responses:  
         200:
          description:
                  <div>
                          Successful
                          <p>Business Error Codes &#58;</p>
                           <table>
                                <tr>
                                  <th>Error code</th>
                                  <th>Error Description</th>
                                </tr>
                                <tr> 
                                  <td>08301</td>
                                  <td>Invalid Account Bank code </td>
                                </tr>
                                <tr> 
                                  <td>08302</td>
                                  <td>Invalid Account type code</td>
                                </tr>
                                <tr> 
                                  <td>08303</td>
                                  <td>Remittance Grouping mode not defined</td>
                                </tr>	
                                <tr> 
                                  <td>08304</td>
                                  <td>Fees grouping mode not defined</td>
                                </tr>	
                                <tr> 
                                  <td>08305</td>
                                  <td>Chargeback grouping mode not defined </td>
                                </tr>	
                                <tr> 
                                  <td>08306</td>
                                  <td>Billing element grouping mode not defined</td>
                                </tr>
                                <tr> 
                                  <td>08307</td>
                                  <td>The length of the bank account number in not correct</td>
                                </tr>	
                                <tr> 
                                  <td>08308</td>
                                  <td>Account link not found for that merchant</td>
                                </tr>	
                                <tr> 
                                  <td>08309</td>
                                  <td>Invalid branch code</td>
                                </tr>	
                                <tr> 
                                  <td>08310</td>
                                  <td>Merchant number not found</td>
                                </tr>	
                                <tr> 
                                  <td>08311</td>
                                  <td>Update not allowed for this merchant, Merchant should have one of the following statues N Normal, S Suspended, M Under Monitoring</td>
                                </tr>	
                                <tr> 
                                  <td>08312</td>
                                  <td>Invalid IBAN code</td>
                                </tr>										
                           </table>
                  </div> 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateMerchantBankAccountRs'                                                                                            
# Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>      
  schemas:
    # --- Import updateMerchantBankAccount request and response 
      UpdateMerchantBankAccountRq:
               $ref: 'request.yaml#/UpdateMerchantBankAccountRq'
      UpdateMerchantBankAccountRs:
               $ref: 'response.yaml#/UpdateMerchantBankAccountRs'                                                                                        
security:
  - bearerAuth: []



