openapi: "3.0.3"
info:
  title: Financial account API documentation
  description: <div><p>Financial account operation management include features for :Financial account, Account transactions and Statements list.</p>
  version: PowerCARD-Issuer V3.5
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:
  #AccountBalance/V2
  /AccountBalance/V2:
      get:
        description:
                    <h3>API Overview</h3>
                    <p>
                        For an existing card or account in the system, Agent as well as customers may request to have more details regarding card account balances (Available & Pending). All these information could be made available for that purpose using this web service.
                    </p>
                    <h3>Functional Description</h3>
                    <img  src="./docs/getAccountBalance.png" />
        summary: Agent as well as customers may request to have more details regarding card account balances.
        tags:
          - Get Account balance.
        parameters:
          - in: query
            name: aliasPAN
            schema:
              type: string
            example: "4250120656063430"
            required: false
            description: The AliasPAN value.
          - in: query
            name: clientCode 
            schema:
              type: string
            required: false
            example: "PWC-CL-WS-RCRD-0005"
            description: The clientCode value.
          - in: query
            name: accountId 
            schema:
              type: string
            required: false
            description: The accountId value.
            example: 198443230
          - in: query
            name: accountType 
            schema:
              type: string
            required: false
            description: The accountType value.
            example: 90
          - in: query
            name: requestUID 
            schema:
              type: string
            required: true
            example: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
            description: Request Identifier. It is sent by the calling system as a universally unique identifier for the message. Used to match response with request messages.
          - in: query
            name: requestDate 
            schema:
              type: string
            required: true
            example: "2018-12-15T00:00:00"
            description: Date when the request was submitted.
          - in: query
            name: userID 
            schema:
              type: string
            required: false
            description: Represents the user Id who made the request.
        responses:  
          200:
            description:
                  <div>
                          Successful
                          <p>Business Error Codes &#58;</p>
                           <table>
                                <tr>
                                  <th>Error code</th>
                                  <th>Error Description</th>
                                </tr>
                                <tr> 
                                  <td>02601</td>
                                  <td>Invalid Card number</td>
                                </tr>
                                <tr> 
                                  <td>02602</td>
                                  <td>Invalid Customer Id</td>
                                </tr>
                                <tr> 
                                  <td>02603</td>
                                  <td>Invalid Internal Account Id</td>
                                </tr>
                                <tr> 
                                  <td>02604</td>
                                  <td>Card product not defined in the system</td>
                                </tr>
                                <tr> 
                                  <td>02605</td>
                                  <td>Invalid Credit Account profile</td>
                                </tr>
                                <tr> 
                                  <td>02606</td>
                                  <td>Invalid Account type</td>
                                </tr>
                                <tr> 
                                  <td>02607</td>
                                  <td>Limits not defined</td>
                                </tr>
                                <tr> 
                                  <td>02608</td>
                                  <td>Error getting the account available balance</td>
                                </tr>								
                           </table>
                  </div> 
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/GetAccountBalanceV35Rs'
              application/xml:
                    schema:
                      $ref: '#/components/schemas/GetAccountBalanceV35Rs'
 # Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>      
  schemas:
      GetAccountBalanceV35Rs:
            $ref: 'response.yaml#/GetAccountBalanceV35Rs'
security:
  - bearerAuth: []