openapi: "3.0.3"
info:
  title: Financial account API documentation
  description: <div><p>Financial account operation management include features for :Financial account, Account transactions and Statements list.</p>
  version: PowerCARD-Issuer V3.5
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:
  #GetFinancialAccountDetails
  /GetFinancialAccountDetails/V3:
        post:
            description:
                        <h3>API Overview</h3>
                          <p>
                              The get financial Account Details web service is an API that can be used to retrieve all maintenance task associated with the account related data provided by the the system. These functions include Account information, Account indicators, Credit line, Account Balances, Direct debit accounts, Custom fields, Communication strategy, Aging, indicators... 
                          </p>
                          <p>
                           The system run some controls on the input data and may reject the operation in case of any data inconsistency.
                          </p>
                        <h3>Functional Description</h3>
                        <img  src="./docs/searchFinancialAccount.png" />
            summary: Retrieve all maintenance task associated with the account related data...
            tags:
              - Get Financial Account Details
            requestBody:
              required: true
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/GetFinancialAccountV35Rq'
                application/xml:
                  schema:
                    $ref: '#/components/schemas/GetFinancialAccountV35Rq'
            responses:  
              200:
                description:
                        <div>
                                Successful
                                <p>Business Error Codes &#58;</p>
                                <table>
                                      <tr>
                                        <th>Error code</th>
                                        <th>Error Description</th>
                                      </tr>
                                      <tr>
                                         <td>30613</td>
                                         <td>Invalid Account Id</td>
                                      </tr>
                                </table>
                        </div> 
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/GetFinancialAccountV35Rs'
                  application/xml:
                    schema:
                      $ref: '#/components/schemas/GetFinancialAccountV35Rs' 
 # Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>      
  schemas:
    # --- Import SearchFinancialAccountV335Rs request and response
      GetFinancialAccountV35Rq:
               $ref: 'request.yaml#/GetFinancialAccountV35Rq'
      GetFinancialAccountV35Rs:
               $ref: 'response.yaml#/GetFinancialAccountV35Rs'
security:
  - bearerAuth: []