openapi: "3.0.3"
info:
  title: Financial account API documentation
  description: <div><p>Financial account operation management include features for :Financial account, Account transactions and Statements list.</p>
  version: PowerCARD-Issuer V3.5
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:
  /SearchFinancialAccount/V3:
        post:
            description:
                        <h3>API Overview</h3>
                          <p>
                          The search financial web service is an API that can be used to retrieve all the financial accounts provided by the the system. this service provides the ability to search for all existing accounts in the system using different criteria’s like Corporate Id, Account Id or also Parent Account Id. 
                          </p>
                          <p>
                          The system run some controls on the input data and may reject the operation in case of any data inconsistency.
                          </p>
                        <h3>Functional Description</h3>
                        <img  src="./docs/searchFinancialAccount.png" />
            summary: The search financial web service can be used to retrieve all the financial accounts...
            tags:
              - Search Financial Account
            requestBody:
              required: true
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/SearchFinancialAccountV335Rq'
                application/xml:
                  schema:
                    $ref: '#/components/schemas/SearchFinancialAccountV335Rq'
            responses:  
              200:
                description:
                        <div>
                                Successful
                                <p>Business Error Codes &#58;</p>
                                <table>
                                      <tr>
                                        <th>Error code</th>
                                        <th>Error Description</th>
                                      </tr>
                                      <tr> 
                                        <td>30611</td>
                                        <td>Invalid Client Code</td>
                                      </tr>
                                       <tr> 
                                        <td>30612</td>
                                        <td>Invalid Corporate Id</td>
                                      </tr>
                                      <tr> 
                                        <td>30613</td>
                                        <td>Invalid Account Id</td>
                                      </tr>   
                                      <tr> 
                                        <td>30614</td>
                                        <td>Parent Account Id</td>
                                      </tr>                                        
                                </table>
                        </div> 
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/SearchFinancialAccountV335Rs' 
                  application/xml:
                          schema:
                            $ref: '#/components/schemas/SearchFinancialAccountV335Rs'
 # Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>      
  schemas:
    # --- Import SearchFinancialAccountV335Rq request and response
      SearchFinancialAccountV335Rq:
               $ref: 'request.yaml#/SearchFinancialAccountV335Rq'
      SearchFinancialAccountV335Rs:
               $ref: 'response.yaml#/SearchFinancialAccountV335Rs'
security:
  - bearerAuth: []