openapi: "3.0.3"
info:
  title: Financial account API documentation
  description: <div><p>Financial account operation management include features for :Financial account, Account transactions and Statements list.</p>
  version: PowerCARD-Issuer V3.5
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:
#SearchObjectMemo  
  /SearchObjectMemo/V2:
        post:
            description:
                        <h3>API Overview</h3>
                          <p>
                            "The search Object Memo web service is an API that can be used to retrieve all memos linked to a given Entity Id and Entity Code.
                            The entities supported by this API are Client, Card, Account and Corporate.
                            As output the web service send back the result of the processing that could be either successfully or unsuccessfully, in what case, the system will share an error code and description for more details."
                            </p>
                        <h3>Functional Description</h3>
                        <img  src="./docs/searchObjectMemo.png" />
            summary: Retrieve all memos linked to a given Entity Id and Entity Code.
            tags:
              - Search Object Memo
            requestBody:
              required: true
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/SearchObjectMemoV35Rq'
                application/xml:
                  schema:
                    $ref: '#/components/schemas/SearchObjectMemoV35Rq'
            responses:  
              200:
                description:
                        <div>
                                Successful
                                <p>Business Error Codes &#58;</p>
                                <table>
                                      <tr>
                                        <th>Error code</th>
                                        <th>Error Description</th>
                                      </tr>
                                      <tr>
                                          <td>12201</td>
                                          <td>Invalid Entity Code</td>
                                      </tr>
                                      <tr>
                                          <td>12202</td>
                                          <td>Invalid Card Number/Token Id</td>
                                      </tr>
                                      <tr>
                                          <td>12203</td>
                                          <td>Invalid Client code</td>
                                      </tr>
                                      <tr>
                                          <td>12204</td>
                                          <td>Invalid Corporate Id</td>
                                      </tr>
                                      <tr>
                                          <td>12205</td>
                                          <td>Invalid account number</td>
                                      </tr>
                                </table>
                        </div> 
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/SearchObjectMemoV35Rs'
                  application/xml:
                      schema:
                        $ref: '#/components/schemas/SearchObjectMemoV35Rs'
 # Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>      
  schemas:
    # --- Import AddObjectMemoV35 request and response
      SearchObjectMemoV35Rq:
               $ref: 'request.yaml#/SearchObjectMemoV35Rq'
      SearchObjectMemoV35Rs:
               $ref: 'response.yaml#/SearchObjectMemoV35Rs'
security:
  - bearerAuth: []