openapi: "3.0.3"
info:
  title: Financial account API documentation
  description: <div><p>Financial account operation management include features for :Financial account, Account transactions and Statements list.</p>
  version: PowerCARD-Issuer V3.5
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:
  # --- TransferAccountToAccount
  /TransferAccountToAccount/V2:
        post:
            description:
                        <h3>API Overview</h3>
                          <p>
                              Transfer Account to Account web service enables customers, agents or any third party to transfer money instantly from a given account to another account in the appropriate currency. The services can be enabled only by providing a limited but important set of details including the source account, destination account, amount, currency… 
                          </p>
                          <p>
                              The operation will debit the source account and credit the destination account with the transfer amount in the right account currency.
                          </p>
                          <p>
                             The system run some controls on the input data and may reject the operation in case of any data inconsistency.
                          </p>
                        <h3>Functional Description</h3>
                         <img  src="./docs/TransferAccountToAccount.png" />
            summary: Transfer money instantly from a given account to another account.
            tags:
              - Transfer Account To Account
            requestBody:
              required: true
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/TransferAccountToAccountV35Rq'
                application/xml:
                  schema:
                    $ref: '#/components/schemas/TransferAccountToAccountV35Rq'
            responses:  
              200:
                description:
                  <div>
                          Successful
                          <p>Business Error Codes &#58;</p>
                           <table>
                                <tr>
                                  <th>Error code</th>
                                  <th>Error Description</th>
                                </tr>
                                <tr> 
                                  <td>16801</td>
                                  <td>Invalid Source Account Number</td>
                                </tr>
                                <tr> 
                                  <td>16802</td>
                                  <td>Invalid destination Account Number</td>
                                </tr>
                                <tr> 
                                  <td>16803</td>
                                  <td>Invalid Amount</td>
                                </tr>
                                <tr> 
                                  <td>16804</td>
                                  <td>Invalid Currency</td>
                                </tr>
                                <tr> 
                                  <td>16805</td>
                                  <td>Invalid Capture Reason Code</td>
                                </tr>
                                <tr> 
                                  <td>16806</td>
                                  <td>Invalid Transaction Code, Please make sure that transaction Codes DT & CT are both defined</td>
                                </tr>
                                <tr> 
                                  <td>16807</td>
                                  <td>Invalid Reversal Flag</td>
                                </tr>
                                <tr> 
                                  <td>16808</td>
                                  <td>Invalid Source Account Status</td>
                                </tr>
                                <tr> 
                                  <td>16809</td>
                                  <td>Invalid destination Account Staus</td>
                                </tr>								
                           </table>
                  </div> 
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/TransferAccountToAccountV35Rs'
                  application/xml:
                    schema:
                      $ref: '#/components/schemas/TransferAccountToAccountV35Rs'        
 # Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>      
  schemas:
   # --- Import TransferAccountToAccountV35 request and response
      TransferAccountToAccountV35Rq:
                      $ref: 'request.yaml#/TransferAccountToAccountV35Rq'
      TransferAccountToAccountV35Rs:
                      $ref: 'response.yaml#/TransferAccountToAccountV35Rs'
security:
  - bearerAuth: []