openapi: "3.0.3"
info:
  title: Payment Instrument API documentation
  description: <p>Payment Instrument and Cardholder operation management include APIs for Payment Instrument maintenance , Payment instrument operations and Status operation.</p>
  version: PowerCARD-Issuer 3.5.4-apiR5.3
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:

  # --- /CheckMerchantExist/V3
  /CheckMerchantExist/V3:
    post:
      description:
        <h3>API Overview</h3>
        <p>
        This API aims to check if a given merchant ID exist or Not in PowerCard Database.
        
        </p>
        <h3>Functional Description</h3>
        <img  src="./docs/CheckMerchantExist.PNG" />
      summary:   A debit card allows the cardholder access to a source of funding that is linked to his/her card.
      tags:
        - Check Merchant Exist
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckMerchantExistRq'
          application/xml:
            schema:
              $ref: '#/components/schemas/CheckMerchantExistRq'
      responses:
        200:
          description:
            <div>
            Successful
            <p>Business Error Codes &#58;</p>
            <table>
            <tr>
            <th>Error code</th>
            <th>Error Description</th>
            </tr>
            <tr>
            <td>60100</td>
            <td>Invalid Merchant Bank Code</td>
            </tr>
            <tr>
            <td>60136</td>
            <td><b>You should specify at least one on this fields:<b> Merchant ID or legal ID</td>
            </tr>
            
            
            
            </table>
            </div>
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckMerchantExistRs'
            application/xml:
              schema:
                $ref: '#/components/schemas/CheckMerchantExistRs'
  # Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description:
        <div>
        <h5>Api key authorization</h5>
        <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
        <table>
        <tr>
        <td>Name &#8282;</td>
        <td>Authorization</td>
        </tr>
        <tr>
        <td>In &#8282;</td>
        <td>Header</td>
        </tr>
        </table>
        </div>
  schemas:

    # --- Import CreateDebitCardV35 request and response
    CheckMerchantExistRq:
      $ref: 'request.yaml#/CheckMerchantExistRq'
    CheckMerchantExistRs:
      $ref: 'response.yaml#/CheckMerchantExistRs'
security:
  - bearerAuth: []