openapi: "3.0.3"
info:
  title: Payment Instrument API documentation
  description: <p>Payment Instrument and Cardholder operation management include APIs for Payment Instrument maintenance , Payment instrument operations and Status operation.</p>
  version: PowerCARD-Issuer 3.5.4-apiR5.3
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:

  # --- /UpdateMerchantAddressDetails/V3
  /UpdateMerchantAddressDetails/V3:
    post:
      description:
        <h3>API Overview</h3>
        <p>
        Using the present web service, users are able to change a merchant address details.
        In PowerCARD, a merchant can have multiple addresses. a mandatory one, also referred to as principal address, also he can have additional addresses for any other delivery purpose. Hence users need then to specify which address is being updated by providing much more details in the request message. In case of any control fail, because for example the postal code is not defined in the system, or because the identification of the address is not found or any other control listed below, the call should be rejected and a specific error code is returned back to the caller for further analysis and correction.
        
        </p>
        <h3>Functional Description</h3>
        <img  src="./docs/updateMerchantAdressDetail.png" />
      summary:   A debit card allows the cardholder access to a source of funding that is linked to his/her card.
      tags:
        - Update Merchant AddressDetails
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateMerchantAddressDetailsRq'
          application/xml:
            schema:
              $ref: '#/components/schemas/UpdateMerchantAddressDetailsRq'
      responses:
        200:
          description:
            <div>
            Successful
            <p>Business Error Codes &#58;</p>
            <table>
            <tr>
            <th>Error Code</th>
            <th>Description</th>
            </tr>
            <tr><td>60100</td><td>Invalid Merchant Bank Code</td></tr>
            <tr><td>60136</td><td>You should specify at least one on this fields:<b> Merchant ID or legal ID</td></tr>
            <tr><td>60200</td><td>Merchant not found</td></tr>
            <tr><td>60300</td><td>Invalid Address default flag</td></tr>
            <tr><td>60301</td><td>Invalid Address Type</td></tr>
            <tr><td>60302</td><td>Invalid Address Default Usage</td></tr>
            <tr><td>60303</td><td>Invalid Address Sending Mode</td></tr>
            <tr><td>60305</td><td>Invalid Address Status Start Date</td></tr>
            <tr><td>60306</td><td>Invalid Address Status End Date</td></tr>
            <tr><td>60307</td><td>Invalid Address Country Code</td></tr>
            <tr><td>60308</td><td>Invalid Address Zip Code</td></tr>
            <tr><td>60309</td><td>Invalid Address Region Code</td></tr>
            <tr><td>60310</td><td>Invalid Address City Code</td></tr>
            <tr><td>60311</td><td>Invalid Address Phone Type</td></tr>
            <tr><td>60312</td><td>Address Fax is required when sending mode is "Fax"</td></tr>
            <tr><td>60313</td><td>Address email is required when sending mode is "Email"</td></tr>
            <tr><td>60314</td><td>Invalid Address URL</td></tr>
            <tr><td>60315</td><td>Invalid address email</td></tr>
            <tr><td>60316</td><td>The address list does not exist with given ID</td></tr>
            <tr><td>60317</td><td>The address details does not exist  with given ID</td></tr>
            <tr><td>60319</td><td>DefaultFlag should be 'Y' for main address</td></tr>
            <tr><td>60320</td><td>Force ZIPCode not allowed on bank addendum params</td></tr>
            <tr><td>60321</td><td>Error while update address informations</td></tr>
            <tr><td>60322</td><td>Invalid address city name</td></tr>
            <tr><td>60323</td><td>Address careof is required</td></tr>
            <tr><td>60325</td><td>The merchant must have only one principal address(default address_flag 'Y') in case multi address, secondary address should have (default address_flag 'N')</td></tr>
            <tr><td>60410</td><td>Bank addendum not found</td></tr>
            <tr><td>60138</td><td>Normal, suspended, under surveillance are the status needed to allow updating</td></tr>
            
            
            
            </table>
            </div>
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateMerchantAddressDetailsRs'
            application/xml:
              schema:
                $ref: '#/components/schemas/UpdateMerchantAddressDetailsRs'
  # Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description:
        <div>
        <h5>Api key authorization</h5>
        <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
        <table>
        <tr>
        <td>Name &#8282;</td>
        <td>Authorization</td>
        </tr>
        <tr>
        <td>In &#8282;</td>
        <td>Header</td>
        </tr>
        </table>
        </div>
  schemas:

    # --- Import CreateDebitCardV35 request and response
    UpdateMerchantAddressDetailsRq:
      $ref: 'request.yaml#/UpdateMerchantAddressDetailsRq'
    UpdateMerchantAddressDetailsRs:
      $ref: 'response.yaml#/UpdateMerchantAddressDetailsRs'
security:
  - bearerAuth: []