openapi: "3.0.3"
info:
  title: Payment Instrument API documentation
  description: <p>Payment Instrument and Cardholder operation management include APIs for Payment Instrument maintenance , Payment instrument operations and Status operation.</p>
  version: PowerCARD-Issuer 3.5.4-apiR5.3
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:

  # --- /UpdateMerchantActivity/V3
  /UpdateMerchantActivity/V3:
    post:
      description:
        <h3>API Overview</h3>
        <p>
        A merchant activity is that which is performed by persons participating in the market to provide goods or services with a monetary value for the purpose of obtaining profit or earnings. This web service is intended to help any user to amend the details of activities of any predefined merchant in the PowerCARD Acquirer database by just providing the merchant activity identification.
        </p>
        <h3>Functional Description</h3>
        <img  src="./docs/updateMerchantActivity.png" />
      summary:   A debit card allows the cardholder access to a source of funding that is linked to his/her card.
      tags:
        - Update Merchant Activity
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateMerchantActivityRq'
          application/xml:
            schema:
              $ref: '#/components/schemas/UpdateMerchantActivityRq'
      responses:
        200:
          description:
            <div>
            Successful
            <p>Business Error Codes &#58;</p>
            <table>
            <tr>
            <th>Error Code</th>
            <th>Description</th>
            </tr>
            <tr><td>60100</td><td>Invalid Merchant Bank Code</td></tr>
            <tr><td>60136</td><td>You should specify at least one on this fields:<b> Merchant ID or legal ID</td></tr>
            <tr><td>60200</td><td>Merchant not found</td></tr>
            <tr><td>60400</td><td>Invalid Activity MCC</td></tr>
            <tr><td>60401</td><td>Invalid Activity Type</td></tr>
            <tr><td>60402</td><td>Invalid Banking Activity Code</td></tr>
            <tr><td>60403</td><td>Invalid Activity Status Code</td></tr>
            <tr><td>60404</td><td>Invalid Activity Status Reason Code</td></tr>
            <tr><td>60405</td><td>Invalid Activity Status Start Date</td></tr>
            <tr><td>60406</td><td>Invalid Activity Status End Date</td></tr>
            <tr><td>60407</td><td>Invalid Activity Opening Date</td></tr>
            <tr><td>60410</td><td>Bank addendum not found</td></tr>
            <tr><td>60411</td><td>Error while update merchant activity</td></tr>
            <tr><td>60412</td><td>Only main activity is allowed</td></tr>
            <tr><td>60414</td><td>Only One primary Activity is Allowed</td></tr>
            <tr><td>60415</td><td>The merchant must have a principal activity</td></tr>
            <tr><td>60416</td><td>Activity with same MCC defined more than once</td></tr>
            <tr><td>60138</td><td>Normal, suspended, under surveillance are the status needed to allow updating</td></tr>
            
            
            </table>
            </div>
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateMerchantActivityRs'
            application/xml:
              schema:
                $ref: '#/components/schemas/UpdateMerchantActivityRs'
  # Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description:
        <div>
        <h5>Api key authorization</h5>
        <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
        <table>
        <tr>
        <td>Name &#8282;</td>
        <td>Authorization</td>
        </tr>
        <tr>
        <td>In &#8282;</td>
        <td>Header</td>
        </tr>
        </table>
        </div>
  schemas:

    # --- Import CreateDebitCardV35 request and response
    UpdateMerchantActivityRq:
      $ref: 'request.yaml#/UpdateMerchantActivityRq'
    UpdateMerchantActivityRs:
      $ref: 'response.yaml#/UpdateMerchantActivityRs'
security:
  - bearerAuth: []