openapi: "3.0.3"
info:
  title: Payment Instrument API documentation
  description: <p>Payment Instrument and Cardholder operation management include APIs for Payment Instrument maintenance , Payment instrument operations and Status operation.</p>
  version: PowerCARD-Issuer 3.5.4-apiR5.3
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:

  # --- /UpdateAcceptorPointDetails/V3
  /UpdateAcceptorPointDetails/V3:
    post:
      description:
        <h3>API Overview</h3>
        <p>
        The present web service is aimed to be used whenever any user would like to update information of specific merchant acceptor point


        <h3>Functional Description</h3>
        <img  src="./docs/GetAcceptorPointDetailss.png" />
      summary:   A debit card allows the cardholder access to a source of funding that is linked to his/her card.
      tags:
        - Update  Acceptor Point Details
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MerAcceptorPointRq'
          application/xml:
            schema:
              $ref: '#/components/schemas/MerAcceptorPointRq'
      responses:
        200:
          description:
            <div>
            Successful
            <p>Business Error Codes &#58;</p>
            <table>
            <tr>
            <th>Error Code</th>
            <th>Description</th>
            </tr>
            <tr><td>60100</td><td>Invalid Merchant Bank Code</td></tr>
            <tr><td>60136</td><td>You should specify at least one on this fields:<b> Merchant ID or legal ID</td></tr>
            <tr><td>60200</td><td>Merchant not found</td></tr>
            <tr><td>60800</td><td>Invalid Contract Element ID</td></tr>
            <tr><td>60801</td><td>Invalid Activity identifier ID</td></tr>
            <tr><td>60802</td><td>Invalid Site Identifier</td></tr>
            <tr><td>60806</td><td>Invalid Acceptor Point ID</td></tr>
            <tr><td>60807</td><td>Error while updating acceptor point information’s</td></tr>
            <tr><td>60122</td><td>Invalid MerchantOnId Identifier</td></tr>
            <tr><td>60123</td><td>Invalid MerchantOnId Value</td></tr>
            
            
            </table>
            </div>
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MerAcceptorPointRs'
            application/xml:
              schema:
                $ref: '#/components/schemas/MerAcceptorPointRs'
  # Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description:
        <div>
        <h5>Api key authorization</h5>
        <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
        <table>
        <tr>
        <td>Name &#8282;</td>
        <td>Authorization</td>
        </tr>
        <tr>
        <td>In &#8282;</td>
        <td>Header</td>
        </tr>
        </table>
        </div>
  schemas:

    # --- Import GetAcceptorPointDetailsRq request and response
    MerAcceptorPointRq:
      $ref: 'request.yaml#/MerAcceptorPointRq'
    MerAcceptorPointRs:
      $ref: 'response.yaml#/MerAcceptorPointRs'
security:
  - bearerAuth: []