openapi: "3.0.3"
info:
  title: Payment Instrument API documentation
  description: <p>Payment Instrument and Cardholder operation management include APIs for Payment Instrument maintenance , Payment instrument operations and Status operation.</p>
  version: PowerCARD-Issuer 3.5.4-apiR5.3
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:

  # --- /UpdateMerchantStatus/V3
  /UpdateMerchantStatus/V3:
    post:
      description:
        <h3>API Overview</h3>
        <p>
        Since the merchant status can vary during the whole life cycle of the merchant, the Update Merchant Status API lets you update the merchant status by providing a status code as well as a status reason used for that change. It also accepts a range date fields that indicate the dates from when and till when the status will be effective.
        </p>
        <h3>Functional Description</h3>
        <img  src="./docs/updateMerchantStatus.png" />
      summary:   A debit card allows the cardholder access to a source of funding that is linked to his/her card.
      tags:
        - Update Merchant Status
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateMerchantStatustRq'
          application/xml:
            schema:
              $ref: '#/components/schemas/UpdateMerchantStatustRq'
      responses:
        200:
          description:
            <div>
            Successful
            <p>Business Error Codes &#58;</p>
            <table>
            <tr>
            <th>Error Code</th>
            <th>Description</th>
            </tr>
            <tr><td>40100</td><td>Invalid Merchant Bank Code</td></tr>
            <tr><td>40136</td><td>You should specify at least one on this fields:<b> Merchant ID or legal ID</td></tr>
            <tr><td>40200</td><td>Merchant not found</td></tr>
            <tr><td>40750</td><td>Error while updating merchant status</td></tr>
            <tr><td>40751</td><td>Invalid Merchant Status</td></tr>
            <tr><td>40752</td><td>Invalid Merchant Status Reason</td></tr>
            <tr><td>40753</td><td>Invalid Merchant Status Start date</td></tr>
            <tr><td>40754</td><td>Invalid Merchant Status end date</td></tr>
            <tr><td>40755</td><td>Invalid Merchant Status range date</td></tr>
            <tr><td>40138</td><td>Normal, suspended, under surveillance are the status needed to allow updating</td></tr>
            
            
            </table>
            </div>
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateMerchantStatusRs'
            application/xml:
              schema:
                $ref: '#/components/schemas/UpdateMerchantStatusRs'
  # Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description:
        <div>
        <h5>Api key authorization</h5>
        <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
        <table>
        <tr>
        <td>Name &#8282;</td>
        <td>Authorization</td>
        </tr>
        <tr>
        <td>In &#8282;</td>
        <td>Header</td>
        </tr>
        </table>
        </div>
  schemas:

    # --- Import CreateDebitCardV35 request and response
    UpdateMerchantStatustRq:
      $ref: 'request.yaml#/UpdateMerchantStatustRq'
    UpdateMerchantStatusRs:
      $ref: 'response.yaml#/UpdateMerchantStatusRs'
security:
  - bearerAuth: []