openapi: "3.0.3"
info:
  title: Payment Tokenization API documentation
  description: <p>Tokenization allows users to store card information in ecommerce solutions and mobile wallets to allow the card to be recharged without exposing the original card information.Tokenization drives innovation. It’s the standard for the card transactions around the world, and PowerCARD Connect’ API system can adapt to sudden changes from emerging technology.</p>         
  version: PowerCARD-Issuer 3.5.4-apiR5.3
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:
  #/v2/tokenRequestors/{tokenRequestorID}/wallets/{waletID}/digitizationRequest
  /v2/tokenRequestors/{tokenRequestorID}/wallets/{waletID}/digitizationRequest:
        post:
            description:
                        <h3>API Overview</h3>
                          <p>
                            This API is used by PowerCARD-Tokenization to request a card digitalization, Issuer send the Information about the payment instrument and the context under which it is provided.
                          </p>
                        <h3>Functional Description</h3>
                        <img  src="./docs/digitizationRequest.png" />
            summary: Request a card digitalization.
            tags:
              - Digitization Request
            requestBody:
              required: true
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/DigitizationRequestV35Rq'
                application/xml:
                  schema:
                    $ref: '#/components/schemas/DigitizationRequestV35Rq'
            responses:  
              200:
                description:
                        <div>
                                Successful
                                <p>Business Error Codes &#58;</p>
                                <table>
                                    <tr>
                                        <th>Error code</th>
                                        <th>Error Description</th>
                                        <tr>
                                        <td>T0601</td>
                                        <td>BankCode </td>
                                        <tr/>
                                        <tr>
                                        <td>T0602</td>
                                        <td>CorrelationId </td>
                                        <tr/>
                                        <tr>
                                        <td>T0603</td>
                                        <td>PaymentInstrumentInfo </td>
                                        <tr/>
                                        <tr>
                                        <td>T0604</td>
                                        <td>PanReferenceID </td>
                                        <tr/>
                                        <tr>
                                        <td>T0605</td>
                                        <td>PanFirstDigits </td>
                                        <tr/>
                                        <tr>
                                        <td>T0606</td>
                                        <td>PanLastDigits </td>
                                        <tr/>
                                        <tr>
                                        <td>T0607</td>
                                        <td>CardholderName </td>
                                        <tr/>
                                </table>
                        </div> 
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/DigitizationRequestV35Rs'
                  application/xml:
                      schema:
                          $ref: '#/components/schemas/DigitizationRequestV35Rs'
 # Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>      
  schemas:
    # --- Import DigitizationRequestV35 request and response
        DigitizationRequestV35Rq:
               $ref: 'request.yaml#/DigitizationRequestV35Rq'
        DigitizationRequestV35Rs:
               $ref: 'response.yaml#/DigitizationRequestV35Rs'
security:
  - bearerAuth: []