openapi: "3.0.3"
info:
  title: PowerCARD-xPos API documentation
  description: <p>HPS’ PowerCARD-xPOS solution can help payments providers, retailers and banks overcome these challenges, and rapidly roll out new services and simply global device deployment, while keeping maintenance and administration costs to a minimum. </p>
  version: PowerCARD 3.2-apiR4.2
servers:
  - url: http://196.12.238.134:12080/PowerCardConnectApi/rest
    description: Development server
paths:
   # ------- createTerminal
  /createTerminal/V1:
    post:
      description:  <h3>API Overview</h3>
                    <p>Users have the ability to create a logical representation of the POS terminal in the system thank to this API. The said API provides functionality to capture a new POS terminal along with set a data that identify uniquely the terminal in the system. Including but not limited to information like floor limit amounts per supported currency, supported languages, POS location…. Please note that in a later stage this terminal need to be assigned uniquely to an existing device with a unique serial number. This association helps to setting up a link between the hardware and its definition in the system.</p>
                    <h3>Functional Description</h3>
                    <img  src="./docs/createTerminal.png" />
                  
      summary: Users have the ability to create a logical representation of the POS terminal...
      tags:
        - Create Terminal
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTerminalRq'
          application/xml:
            schema:
              $ref: '#/components/schemas/CreateTerminalRq'
      responses:  
         200:
          description:
                  <div>
                          Successful
                          <p>Business Error Codes &#58;</p>
                           <table>
                              <tr>
                                <th>Error code</th>
                                <th>Error Description</th>
                              </tr>
                              <tr> 
                                <td>05401</td>
                                <td>Invalid operation type</td>
                              </tr>
                              <tr> 
                                <td>05402</td>
                                <td>Terminal Pos number already exists </td>
                              </tr>
                              <tr> 
                                <td>05403</td>
                                <td>Invalid terminal pos number</td>
                              </tr>
                              <tr> 
                                <td>05404</td>
                                <td>Invalid Master pos indicator </td>
                              </tr>
                              <tr> 
                                <td>05405</td>
                                <td>Pos profile not found </td>
                              </tr>
                              <tr> 
                                <td>05406</td>
                                <td>Invalid outlet number </td>
                              </tr>	
                              <tr> 
                                <td>05407</td>
                                <td>The values provided in country, region and city are not coherent </td>
                              </tr>	
                              <tr> 
                                <td>05408</td>
                                <td>Pos location is not provided</td>
                              </tr>	
                              <tr> 
                                <td>05409</td>
                                <td>Invalid pulse flag </td>
                              </tr>	
                              <tr> 
                                <td>05410</td>
                                <td>Master pos number is null </td>
                              </tr>	
                              <tr> 
                                <td>05411</td>
                                <td>Invalid protocol index </td>
                              </tr>	
                              <tr> 
                                <td>05412</td>
                                <td>Invalid pos soft </td>
                              </tr>	
                              <tr> 
                                <td>05413</td>
                                <td>Invalid transaction processing mode </td>
                              </tr>	
                              <tr> 
                                <td>05414</td>
                                <td>Invalid terminal pos grouping </td>
                              </tr>	
                              <tr> 
                                <td>05415</td>
                                <td>Dial hour is null</td>
                              </tr>	
                              <tr> 
                                <td>05416</td>
                                <td>Invalid stop list parameters</td>
                              </tr>
                              <tr> 
                                <td>05417</td>
                                <td>Invalid terminal mode status </td>
                              </tr>	
                              <tr> 
                                <td>05418</td>
                                <td>Invalid credit note flag </td>
                              </tr>		
                              <tr> 
                                <td>05419</td>
                                <td>Invalid currency code </td>
                              </tr>		
                              <tr> 
                                <td>05420</td>
                                <td>First currency code is null </td>
                              </tr>		
                              <tr> 
                                <td>05421</td>
                                <td>First language code is null </td>
                              </tr>
                              <tr> 
                                <td>05422</td>
                                <td>Invalid language code </td>
                              </tr>	
                              <tr> 
                                <td>05423</td>
                                <td>Terminal Pos number not generated </td>
                              </tr>	
                              <tr> 
                                <td>05424</td>
                                <td>Terminal Amount list structure is empty </td>
                              </tr>	
                              <tr> 
                                <td>05425</td>
                                <td>Master Pos number not found</td>
                              </tr>								
                           </table>
                  </div> 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateTerminalRs'
         401:
          description: 401 Unauthorized - The PowerCard User passed in the token is invalid. Client should refresh the token and then try again.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateTerminalRs'
         404:
          description: 404 Not Found - PowerCARD Resource not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateTerminalRs'
         415:
          description: 415 Unsupported Media Type - Returned when the the format you requested is not supported for the PowerCARD Resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateTerminalRs'  
         500:
          description: 500 Internal Server Error - Servers are not working as expected. The request is probably valid but needs to be requested again later.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateTerminalRs'
         504:
          description: A service required to fulfill the request was not available.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateTerminalRs'                                                                
# Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>
  schemas:
    # --- Import CreateTerminal request and response
      CreateTerminalRq:
               $ref: 'request.yaml#/CreateTerminalRq'
      CreateTerminalRs:
               $ref: 'response.yaml#/CreateTerminalRs'    
security:
  - bearerAuth: []
  