openapi: "3.0.3"
info:
  title: PowerCARD-xPos API documentation
  description: <p>HPS’ PowerCARD-xPOS solution can help payments providers, retailers and banks overcome these challenges, and rapidly roll out new services and simply global device deployment, while keeping maintenance and administration costs to a minimum. </p>
  version: PowerCARD 3.2-apiR4.2
servers:
  - url: http://196.12.238.134:12080/PowerCardConnectApi/rest
    description: Development server
paths:
  # ------- createDevice
  /createDevice/V1:
    post:
      description:  <h3>API Overview</h3>
                    <p>The create device API provides functionality to add a new device definition in the system. The device details sent in the request message include information concerning the machine being captured in the system, like its serial number, brand name, purchase date… Please note that in a later stage this device will be allocated to a logical POS terminal number. This association helps to setting up a link between the hardware or a device and its definition in the system.</p>
                    <h3>Functional Description</h3>
                    <img  src="./docs/createDevice.png" />
                  
      summary: The create device API provides functionality to add a new device definition in the system.
      tags:
        - Create Device
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateDeviceRq'
          application/xml:
            schema:
              $ref: '#/components/schemas/CreateDeviceRq'
      responses:  
         200:
          description:
                  <div>
                          Successful
                          <p>Business Error Codes &#58;</p>
                           <table>
                                <tr>
                                  <th>Error code</th>
                                  <th>Error Description</th>
                                </tr>
                                <tr> 
                                  <td>05301</td>
                                  <td>Invalid Operation Type</td>
                                </tr>
                                <tr> 
                                  <td>05302</td>
                                  <td>Invalid bank Code</td>
                                </tr>
                                <tr> 
                                  <td>05303</td>
                                  <td>Invalid Pos Brand Code</td>
                                </tr>
                                <tr> 
                                  <td>05304</td>
                                  <td>Invalid Serial Number</td>
                                </tr>
                                <tr> 
                                  <td>05305</td>
                                  <td>Invalid Device Status</td>
                                </tr>
                                <tr> 
                                  <td>05306</td>
                                  <td>Invalid Currency Code </td>
                                </tr>
                                <tr> 
                                  <td>05307</td>
                                  <td>Device already exists in the system</td>
                                </tr>
                                <tr> 
                                  <td>05308</td>
                                  <td>Device not found</td>
                                </tr>														
                           </table>
                  </div> 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateDeviceRs'
         401:
          description: 401 Unauthorized - The PowerCard User passed in the token is invalid. Client should refresh the token and then try again.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateDeviceRs'
         404:
          description: 404 Not Found - PowerCARD Resource not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateDeviceRs'
         415:
          description: 415 Unsupported Media Type - Returned when the the format you requested is not supported for the PowerCARD Resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateDeviceRs'  
         500:
          description: 500 Internal Server Error - Servers are not working as expected. The request is probably valid but needs to be requested again later.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateDeviceRs'
         504:
          description: A service required to fulfill the request was not available.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateDeviceRs'                                                                    
# Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>
  schemas:
    # --- Import CreateDevice request and response
      CreateDeviceRq:
               $ref: 'request.yaml#/CreateDeviceRq'
      CreateDeviceRs:
               $ref: 'response.yaml#/CreateDeviceRs'    
         
security:
  - bearerAuth: []
  