openapi: "3.0.3"
info:
  title: PowerCARD-xPos API documentation
  description: <p>HPS’ PowerCARD-xPOS solution can help payments providers, retailers and banks overcome these challenges, and rapidly roll out new services and simply global device deployment, while keeping maintenance and administration costs to a minimum. </p>
  version: PowerCARD 3.2-apiR4.2
servers:
  - url: http://196.12.238.134:12080/PowerCardConnectApi/rest
    description: Development server
paths:
  # ------- getDevice
  /getDevice/V1:
    post:
      description:  <h3>API Overview</h3>
                    <p>The get device API provides functionality to retrieve information with regards to a given device. Data returned in the response message should include data like the POS brand, the serial number, the device status…</p>
                    <h3>Functional Description</h3>
                    <img  src="./docs/getDevice.png" />
                  
      summary: The get device API provides functionality to retrieve information with regards to a given device.
      tags:
        - Get Device
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetDeviceRq'
          application/xml:
            schema:
              $ref: '#/components/schemas/GetDeviceRq'
      responses:  
         200:
          description:
                  <div>
                          Successful
                          <p>Business Error Codes &#58;</p>
                           <table>
                              <tr>
                                <th>Error code</th>
                                <th>Error Description</th>
                              </tr>
                              <tr> 
                                <td>05901</td>
                                <td>Invalid bank code</td>
                              </tr>
                              <tr> 
                                <td>05902</td>
                                <td>Device and terminal not found</td>
                              </tr>
                              <tr> 
                                <td>05903</td>
                                <td>Device multi allocated to terminal</td>
                              </tr>													
                           </table>
                  </div>
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetDeviceRs'
         401:
          description: 401 Unauthorized - The PowerCard User passed in the token is invalid. Client should refresh the token and then try again.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetDeviceRs'
         404:
          description: 404 Not Found - PowerCARD Resource not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetDeviceRs'
         415:
          description: 415 Unsupported Media Type - Returned when the the format you requested is not supported for the PowerCARD Resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetDeviceRs'  
         500:
          description: 500 Internal Server Error - Servers are not working as expected. The request is probably valid but needs to be requested again later.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetDeviceRs'
         504:
          description: A service required to fulfill the request was not available.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetDeviceRs'                                                                   
# Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>
  schemas:
    # --- Import GetDeviceRq request and response
      GetDeviceRq:
               $ref: 'request.yaml#/GetDeviceRq'
      GetDeviceRs:
               $ref: 'response.yaml#/GetDeviceRs'       
         
security:
  - bearerAuth: []
  