openapi: "3.0.3"
info:
  title: PowerCARD-xPos API documentation
  description: <p>HPS’ PowerCARD-xPOS solution can help payments providers, retailers and banks overcome these challenges, and rapidly roll out new services and simply global device deployment, while keeping maintenance and administration costs to a minimum. </p>
  version: PowerCARD 3.2-apiR4.2
servers:
  - url: http://196.12.238.134:12080/PowerCardConnectApi/rest
    description: Development server
paths:
   # ------- returnDevice
  /returnDevice/V1:
    post:
      description:  <h3>API Overview</h3>
                    <p>Returning a device for reparation purpose for instance is translated by setting the status of the device to the new value sent in the request.</p>
                    <h3>Functional Description</h3>
                   <img  src="./docs/returnDevice.png" />
                  
      summary: Returning a device for reparation purpose for instance is translated by setting the status of the device
      tags:
        - Return Device
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReturnDeviceRq'
          application/xml:
            schema:
              $ref: '#/components/schemas/ReturnDeviceRq'
      responses:  
         200:
          description:
                  <div>
                          Successful
                          <p>Business Error Codes &#58;</p>
                           <table>
                                <tr>
                                  <th>Error code</th>
                                  <th>Error Description</th>
                                </tr>
                                <tr> 
                                  <td>05701</td>
                                  <td>Not used</td>
                                </tr>
                                <tr> 
                                  <td>05702</td>
                                  <td>Not used</td>
                                </tr>
                                <tr> 
                                  <td>05703</td>
                                  <td>Invalid terminal Pos Number </td>
                                </tr>
                                <tr> 
                                  <td>05704</td>
                                  <td>The terminal is not allocated</td>
                                </tr>
                                <tr> 
                                  <td>05705</td>
                                  <td>Invalid Pos Reason Back Code</td>
                                </tr>
                                <tr> 
                                  <td>05706</td>
                                  <td>Error occurred when returning the terminal details, please contact the administrator</td>
                                </tr>							
                           </table>
                  </div> 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReturnDeviceRs'
         401:
          description: 401 Unauthorized - The PowerCard User passed in the token is invalid. Client should refresh the token and then try again.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReturnDeviceRs'
         404:
          description: 404 Not Found - PowerCARD Resource not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReturnDeviceRs'
         415:
          description: 415 Unsupported Media Type - Returned when the the format you requested is not supported for the PowerCARD Resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReturnDeviceRs'  
         500:
          description: 500 Internal Server Error - Servers are not working as expected. The request is probably valid but needs to be requested again later.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReturnDeviceRs'
         504:
          description: A service required to fulfill the request was not available.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReturnDeviceRs'                                                               
# Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>
  schemas:
    # --- Import ReturnDevice request and response
      ReturnDeviceRq:
               $ref: 'request.yaml#/ReturnDeviceRq'
      ReturnDeviceRs:
               $ref: 'response.yaml#/ReturnDeviceRs'   
         
security:
  - bearerAuth: []
  