openapi: "3.0.3"
info:
  title: Loan API documentation
  description: <p> PowerCARD Connect’API offers through APIs specific functions to access to the Loan function. This function is used to view the details of Loan’s operations including Loan Search ,Loan Cancellation...</p>
  version: PowerCARD-Issuer V3.5
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:
  #convertTransactionToLoan  
  /ConvertTransactionToloan/V2:
        post:
            description:
                        <h3>API Overview</h3>
                          <p>
                          The main purpose of this web service is to convert normal transactions to loans. Loan program, reason and transaction Identifier are one of required fields.
                          </p>
                        <h3>Functional Description</h3>
                        <img  src="./docs/convertTransactionToLoan.png" />
            summary: Convert normal transactions to loans.
            tags:
              - Convert Transaction To Loan.
            requestBody:
              required: true
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/ConvertTransactionToLoanV35Rq'
                application/xml:
                  schema:
                    $ref: '#/components/schemas/ConvertTransactionToLoanV35Rq'
            responses:  
              200:
                description:
                        <div>
                                Successful
                                <p>Business Error Codes &#58;</p>
                                <table>
                                      <tr>
                                        <th>Error code</th>
                                        <th>Error Description</th>
                                      </tr>
                                      <tr>
                                        <td>18901</td>
                                        <td>Invalid Loan Program Code</td>
                                      </tr>
                                      <tr>
                                        <td>18902</td>
                                        <td>Invalid Reason Code</td>
                                      </tr>
                                      <tr>
                                        <td>18903</td>
                                        <td>Invalid Transaction Flag</td>
                                      </tr>
                                      <tr>
                                        <td>18904</td>
                                        <td>Invalid Transaction Id</td>
                                      </tr>
                                      <tr>
                                        <td>18905</td>
                                        <td>Invalid Reference Sequence</td>
                                      </tr>
                                      <tr>
                                        <td>18906</td>
                                        <td>Reserved for future use</td>
                                      </tr>
                                       <tr>
                                        <td>18907</td>
                                        <td>Reserved for future use</td>
                                      </tr>
                                      <tr>
                                        <td>18908</td>
                                        <td>Reserved for future use</td>
                                      </tr>
                                      <tr>
                                        <td>18909</td>
                                        <td>Reserved for future use</td>
                                      </tr>
                                      <tr>
                                        <td>18910</td>
                                        <td>Reserved for future use</td>
                                      </tr>
                                      <tr>
                                        <td>18911</td>
                                        <td>Transaction cannot be converted</td>
                                      </tr>
                                      <tr>
                                        <td>18912</td>
                                        <td>Program Code not allowed</td>
                                      </tr>
                                      <tr>
                                        <td>18913</td>
                                        <td>Internal Error while performing the conversion request</td>
                                      </tr>
                                      <tr>
                                        <td>18914</td>
                                        <td>Loan limit exceeded</td>
                                      </tr>
                                </table>
                        </div> 
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/ConvertTransactionToLoanV35Rs'
                  application/xml:
                      schema:
                        $ref: '#/components/schemas/ConvertTransactionToLoanV35Rs'        
 # Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>      
  schemas:
    # --- Import UpdateCustomerCategoryV35 request and response
      ConvertTransactionToLoanV35Rq:
               $ref: 'request.yaml#/ConvertTransactionToLoanV35Rq'
      ConvertTransactionToLoanV35Rs:
               $ref: 'response.yaml#/ConvertTransactionToLoanV35Rs'
security:
  - bearerAuth: []