openapi: "3.0.3"
info:
  title: Loan API documentation
  description: <p> PowerCARD Connect’API offers through APIs specific functions to access to the Loan function. This function is used to view the details of Loan’s operations including Loan Search ,Loan Cancellation...</p>
  version: PowerCARD-Issuer V3.5
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:
  #getInstallmentPlan  
  /GetInstallmentplan/V2:
        post:
            description:
                        <h3>API Overview</h3>
                          <p>
                          The get installment plan web service is an API that can be used to get the installment plan of a given loan transaction provided by the loan company to the customer. Whether it is an ongoing loan or an amortized one, this service provides the ability to search for a specific loan in the system using the transaction reference Number and sequence, two fields used internally by PowerCARD to identify uniquely a transaction in the system.
                          </p>
                        <h3>Functional Description</h3>
                        <img  src="./docs/getInstallmentPlan.png" />
            summary: Get the installment plan of a given loan transaction... 
            tags:
              - Get Installment Plan.
            requestBody:
              required: true
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/GetInstallmentPlanV35Rq'
                application/xml:
                  schema:
                    $ref: '#/components/schemas/GetInstallmentPlanV35Rq'
            responses:  
              200:
                description:
                        <div>
                                Successful
                                <p>Business Error Codes &#58;</p>
                                <table>
                                      <tr>
                                        <th>Error code</th>
                                        <th>Error Description</th>
                                      </tr>
                                      <tr>
                                          <td>18101</td>
                                          <td>Installment plan / Loan not found in the system</td>
                                      </tr>
                                </table>
                        </div> 
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/GetInstallmentPlanV35Rs'
                  application/xml:
                      schema:
                        $ref: '#/components/schemas/GetInstallmentPlanV35Rs'                
 # Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>      
  schemas:
    # --- Import GetInstallmentPlanV35 request and response
      GetInstallmentPlanV35Rq:
               $ref: 'request.yaml#/GetInstallmentPlanV35Rq'
      GetInstallmentPlanV35Rs:
               $ref: 'response.yaml#/GetInstallmentPlanV35Rs'
security:
  - bearerAuth: []