openapi: "3.0.3"
info:
  title: Loan API documentation
  description: <p> PowerCARD Connect’API offers through APIs specific functions to access to the Loan function. This function is used to view the details of Loan’s operations including Loan Search ,Loan Cancellation...</p>
  version: PowerCARD-Issuer V3.5
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:
#loanCancellation  
  /loanCancellation/V2:
        post:
            description:
                        <h3>API Overview</h3>
                          <p>
                              The loan cancellation web service is an API that can be used to force closure of a loan. The loan is identified  by account number / card number , ARN number and sequence . <br>
                              All billed installment/interest/fees will be cancelled however the unbilled installments will be deactivated and moved to the history and the Loan booking fee will be cancelled. <br>
                              The following sections are intended to highlight the process as well as the technical specification of the request and response messages. <br>
                          </p>
                        <h3>Functional Description</h3>
                        <img  src="./docs/loanCancellation.png" />
            summary: The loan cancellation web service is an API that can be used to force closure of a loan.
            tags:
              - Loan Cancellation
            requestBody:
              required: true
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/LoanCancellationV35Rq'
                application/xml:
                  schema:
                    $ref: '#/components/schemas/LoanCancellationV35Rq'
            responses:  
              200:
                description:
                        <div>
                                Successful
                                <p>Business Error Codes &#58;</p>
                                <table>
                                      <tr>
                                        <th>Error code</th>
                                        <th>Error Description</th>
                                      </tr>
                                      <tr>
                                          <td>41501</td>
                                          <td>Invalid Account Id</td>
                                      </tr>
                                      <tr>
                                          <td>41502</td>
                                          <td>Invalid Transaction Id</td>
                                      </tr>
                                      <tr>
                                          <td>41503</td>
                                          <td>Invalid Reference Sequence</td>
                                      </tr>
                                      <tr>
                                          <td>41504</td>
                                          <td>Invalid Reason Code</td>
                                      </tr>
                                </table>
                        </div> 
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/LoanCancellationV35Rs'
                  application/xml:
                      schema:
                        $ref: '#/components/schemas/LoanCancellationV35Rs'         
 # Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>      
  schemas:
    # --- Import LoanCancellationV35 request and response
      LoanCancellationV35Rq:
               $ref: 'request.yaml#/LoanCancellationV35Rq'
      LoanCancellationV35Rs:
               $ref: 'response.yaml#/LoanCancellationV35Rs'    
security:
  - bearerAuth: []