openapi: "3.0.3"
info:
  title: Loan API documentation
  description: <p> PowerCARD Connect’API offers through APIs specific functions to access to the Loan function. This function is used to view the details of Loan’s operations including Loan Search ,Loan Cancellation...</p>
  version: PowerCARD-Issuer V3.5
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:
  #SimulateLoan  
  /SimulateLoan/V2:
        post:
            description:
                        <h3>API Overview</h3>
                          <p>
                           This web service can be invoked before a loan booking. It returns a loan simulation that can be verified by the agent and agreed with the customer before booking a loan.. <br>
                           The following sections are intended to highlight the process as well as the technical specification of the request and response messages.  
                          </p>
                        <h3>Functional Description</h3>
                        <img  src="./docs/SimulateLoan.png" />
            summary: It returns a loan simulation that can be verified by the agent...
            tags:
              - Simulate Loan.
            requestBody:
              required: true
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/SimulateLoanV35Rq'
                application/xml:
                  schema:
                    $ref: '#/components/schemas/SimulateLoanV35Rq'
            responses:  
              200:
                description:
                        <div>
                                Successful
                                <p>Business Error Codes &#58;</p>
                                <table>
                                      <tr>
                                        <th>Error code</th>
                                        <th>Error Description</th>
                                      </tr>
                                      <tr>
                                        <td>41601</td>
                                        <td>Invalid Card Number/Token Id</td>
                                      </tr>
                                      <tr>
                                        <td>41602</td>
                                        <td>Invalid Account Id</td>
                                      </tr>
                                      <tr>
                                        <td>41603</td>
                                        <td>Invalid Transaction Id</td>
                                      </tr>
                                       <tr>
                                        <td>41604</td>
                                        <td>Invalid Reference Sequence</td>
                                      </tr>
                                       <tr>
                                        <td>41605</td>
                                        <td>Invalid Catalog Loan Product</td>
                                      </tr>
                                      <tr>
                                        <td>41606</td>
                                        <td>Invalid Catalog Loan Product</td>
                                      </tr>
                                </table>
                        </div> 
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/SimulateLoanV35Rs'
                  application/xml:
                      schema:
                        $ref: '#/components/schemas/SimulateLoanV35Rs'                
 # Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>      
  schemas:
    # --- Import SimulateLoanV35 request and response
      SimulateLoanV35Rq:
               $ref: 'request.yaml#/SimulateLoanV35Rq'
      SimulateLoanV35Rs:
               $ref: 'response.yaml#/SimulateLoanV35Rs'
security:
  - bearerAuth: []