openapi: "3.0.3"
info:
  title: Financial account API documentation
  description: <div><p>Financial account operation management include features for :Financial account, Account transactions and Statements list.</p>
  version: PowerCARD-Issuer V3.5
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:
  #changeAccountBillingCycle    
  /ChangeAccountbillingCycle/V2:
        post:
            description:
                        <h3>API Overview</h3>
                          <p>
                               For a credit account, a billing cycle is defined as the time between the last bill and the most current one. <br>
                               The purpose of this web service is to allow changing the account billing cycle date by providing a code identifying the cycle date in PowerCARD. Many reasons can be given to justify the billing cycle change, for instance the customer might need to simplify his payment schedule by setting a new date for his billing cycle.<br>
                               It is important to note that the change will takes effect only starting from the next cycle. This Web Service can be called by a customer or an agent.
                          </p>
                        <h3>Functional Description</h3>
                        <img  src="./docs/changeAccountBillingCycle.png" />
            summary:  Change time between the last bill and the most current one.
            tags:
              - Change Account Billing Cycle
            requestBody:
              required: true
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/ChangeAccountBillingCycle35Rq'
                application/xml:
                  schema:
                    $ref: '#/components/schemas/ChangeAccountBillingCycle35Rq'
            responses:  
              200:
                description:
                        <div>
                                Successful
                                <p>Business Error Codes &#58;</p>
                                <table>
                                      <tr>
                                        <th>Error code</th>
                                        <th>Error Description</th>
                                      </tr>
                                      <tr> 
                                        <td>09801</td>
                                        <td>Invalid Account Number</td>
                                      </tr>
                                       <tr> 
                                        <td>09802</td>
                                        <td>Invalid Account Status</td>
                                      </tr>
                                      <tr> 
                                        <td>09803</td>
                                        <td>Invalid Billing Cycle Code</td>
                                      </tr>
                                      <tr> 
                                        <td>09804</td>
                                        <td>Change not allowed</td>
                                      </tr>                                      
                                </table>
                        </div> 
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/ChangeAccountBillingCycle35Rs' 
                  application/xml:
                          schema:
                            $ref: '#/components/schemas/ChangeAccountBillingCycle35Rs'   
 # Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>      
  schemas:
    # --- Import ChangeAccountBillingCycle35 request and response
      ChangeAccountBillingCycle35Rq:
               $ref: 'request.yaml#/ChangeAccountBillingCycle35Rq'
      ChangeAccountBillingCycle35Rs:
               $ref: 'response.yaml#/ChangeAccountBillingCycle35Rs'  
security:
  - bearerAuth: []