openapi: "3.0.3"
info:
  title: Financial account API documentation
  description: <div><p>Financial account operation management include features for :Financial account, Account transactions and Statements list.</p>
  version: PowerCARD-Issuer V3.5
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:
  #changeAccountCreditLimit
  /ChangeAccountCreditLimit/V2:
        post:
            description:
                        <h3>API Overview</h3>
                          <p>
                              The credit limit is defined as the maximum amount of money that can be spent on a credit card. The Change credit limit web service could be used to either increase or decrease the credit limit on an existing account. The same web service could be also used to set temporary limits with a specified range of date.
                          </p>
                          <p>This Web Service can be called by a customer or an agent.</p>
                        <h3>Functional Description</h3>
                        <img  src="./docs/changeAccountCreditLimit.png" />
            summary: This Web Service can be called by a customer or an agent.
            tags:
              - Change Account Credit Limit 
            requestBody:
              required: true
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/ChangeAccountCreditLimitV35Rq'
                application/xml:
                  schema:
                    $ref: '#/components/schemas/ChangeAccountCreditLimitV35Rq'
            responses:  
              200:
                description:
                        <div>
                                Successful
                                <p>Business Error Codes &#58;</p>
                                <table>
                                      <tr>
                                        <th>Error code</th>
                                        <th>Error Description</th>
                                      </tr>
                                      <tr>  
                                         <td>03501</td>
                                         <td>Invalid Account Number</td>
                                      </tr>
                                      <tr>  
                                         <td>03502</td>
                                         <td>Credit limit is less than the cash limit</td>
                                      </tr>
                                      <tr>  
                                         <td>03503</td>
                                         <td>Cash limit should be equal to or less than cash limit ceiling, contact your administrator</td>
                                      </tr>  
                                      <tr>  
                                         <td>03504</td>
                                         <td>Loan limit should be equal to or less than loan limit ceiling, contact your administrator</td>
                                      </tr> 
                                      <tr>  
                                         <td>03505</td>
                                         <td>Invalid Currency Code</td>
                                      </tr>  
                                      <tr>  
                                         <td>03506</td>
                                         <td>Invalid Shadow Account profile code</td>
                                      </tr>                                                                                                              
                                </table>
                        </div> 
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/ChangeAccountCreditLimitV35Rs' 
                  application/xml:
                          schema:
                            $ref: '#/components/schemas/ChangeAccountCreditLimitV35Rs'               
 # Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>      
  schemas:
    # --- Import ChangeAccountCreditLimitV35 request and response
      ChangeAccountCreditLimitV35Rq:
               $ref: 'request.yaml#/ChangeAccountCreditLimitV35Rq'
      ChangeAccountCreditLimitV35Rs:
               $ref: 'response.yaml#/ChangeAccountCreditLimitV35Rs' 
security:
  - bearerAuth: []