openapi: "3.0.3"
info:
  title: Financial account API documentation
  description: <div><p>Financial account operation management include features for :Financial account, Account transactions and Statements list.</p>
  version: PowerCARD-Issuer V3.5
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:
   #createAccountTransaction
  /CreateAccountTransaction/V2:
      post:
        description:
                    <h3>API Overview</h3>
                    <p>
                      Users (Agents or bank customers) can use this web service to create and post a transaction to an existing account in the system.
                    </p>
                    <p>
                        For every single transaction that the user would like to create, 
                        he needs to specify at lease the following information in the request message Card Number or Account number,
                        Transaction code, Amount, Date. Transaction is then created in the system but will wait for the End of day processing to be completely posted to the account.<br>
                        We should note that both debit and credit transactions could be created using this web service.
                    </p>
                    <h3>Functional Description</h3>
                    <img  src="./docs/CreateAccountTransaction.png" />
        summary: Create and post a transaction to an existing account in the system.
        tags:
          - Create Account Transaction.
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateAccountTransactionV35Rq'
            application/xml:
              schema:
                $ref: '#/components/schemas/CreateAccountTransactionV35Rq'
        responses:  
          200:
            description:
                  <div>
                          Successful
                          <p>Business Error Codes &#58;</p>
                           <table>
                                <tr>
                                  <th>Error code</th>
                                  <th>Error Description</th>
                                </tr>
                                <tr> 
                                  <td>11001</td>
                                  <td>Invalid Account Number</td>
                                </tr>
                                <tr> 
                                  <td>11002</td>
                                  <td>Invalid Account Status</td>
                                </tr>
                                <tr> 
                                  <td>11003</td>
                                  <td>Invalid Transaction Code</td>
                                </tr>
                                <tr> 
                                  <td>11004</td>
                                  <td>Invalid Transaction Amount</td>
                                </tr>
                                <tr> 
                                  <td>11005</td>
                                  <td>Invalid Transaction date</td>
                                </tr>
                                <tr> 
                                  <td>11006</td>
                                  <td>Invalid Card number</td>
                                </tr>
                                <tr> 
                                  <td>11007</td>
                                  <td>Card number and Account number are both missing</td>
                                </tr>
                                <tr> 
                                  <td>11008</td>
                                  <td>Card account link not found</td>
                                </tr>
                                <tr> 
                                  <td>11009</td>
                                  <td>Multiple Card account links found</td>
                                </tr>
                                <tr> 
                                  <td>11010</td>
                                  <td>Invalid Reversal Flag</td>
                                </tr>	
                                <tr> 
                                  <td>11011</td>
                                  <td>Original transaction not found</td>
                                </tr>	
                                <tr> 
                                  <td>11012</td>
                                  <td>Invalid value date</td>
                                </tr>	
                                <tr> 
                                  <td>11013</td>
                                  <td>Invalid Reason Code</td>
                                </tr>	
                                <tr> 
                                  <td>11014</td>
                                  <td>Invalid Currency Code</td>
                                </tr>							
                           </table>
                  </div> 
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/CreateAccountTransactionV35Rs'
              application/xml:
                    schema:
                      $ref: '#/components/schemas/CreateAccountTransactionV35Rs'   
 # Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>      
  schemas:
    # ---- Import CreateAccountTransactionV35 request and response definition
      CreateAccountTransactionV35Rq:
           $ref: 'request.yaml#/CreateAccountTransactionV35Rq'
      CreateAccountTransactionV35Rs:
           $ref: 'response.yaml#/CreateAccountTransactionV35Rs'
security:
  - bearerAuth: []