openapi: "3.0.3"
info:
  title: Payment Instrument API documentation
  description: <p>Payment Instrument and Cardholder operation management include APIs for Payment Instrument maintenance , Payment instrument operations and Status operation.</p>
  version: PowerCARD-Issuer 3.5.4-apiR5.3
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:
  /webhooks/v1/:
    delete:
      description:
        <h3>API Overview</h3>
        <p>
             This web service can be used to remove webhooks endpoints in the system.
        </p>
      summary: This web service can be used to register and manage webhooks endpoints in the system.
      tags:
        - Delete webhook endpoint.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteWebhook35Rq'
          application/xml:
            schema:
              $ref: '#/components/schemas/DeleteWebhook35Rq'
      responses:
        200:
          description:
            <div>
            Successful
            <p>Business Error Codes &#58;</p>
            <table>
            <tr>
            <th>Error code</th>
            <th>Error Description</th>
            </tr>
            </table>
            </div>
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/deleteWebhook35Rs'
            application/xml:
              schema:
                $ref: '#/components/schemas/deleteWebhook35Rs'
 # Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>      
  schemas:
    DeleteWebhook35Rq:
               $ref: 'request.yaml#/DeleteWebhook35Rq'
    deleteWebhook35Rs:
                $ref: 'response.yaml#/deleteWebhook35Rs'
security:
  - bearerAuth: []