openapi: "3.0.3"
info:
  title: Financial account API documentation
  description: <div><p>Financial account operation management include features for :Financial account, Account transactions and Statements list.</p>
  version: PowerCARD-Issuer V3.5
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:
  #BankAccount/V2 
  /BankAccount/V2:
        patch:
            description:
                        <h3>API Overview</h3>
                          <p>
                            This web services is aimed to update bank account information. Agent as well as customers can ask to add, edit or delete one or multiple bank account in the system. It is important to note that the web service requires either the card number or the credit account number for which the adjustment will be performed. As output the web service send back the result of the processing that could be either successfully or unsuccessfully, in what case, the system will share an error code and description for more details.
                          </p>
                        <h3>Functional Description</h3>
                        <img  src="./docs/UpdateBankAccount.png" />
            summary: Agent as well as customers can ask to add, edit or delete one or multiple bank account. 
            tags:
              - Update Bank Account.
            requestBody:
              required: true
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/UpdateBankAccountV35Rq'
                application/xml:
                  schema:
                    $ref: '#/components/schemas/UpdateBankAccountV35Rq'
            responses:  
              200:
                description:
                        <div>
                                Successful
                                <p>Business Error Codes &#58;</p>
                                <table>
                                      <tr>
                                        <th>Error code</th>
                                        <th>Error Description</th>
                                      </tr>
                                      <tr> 
                                        <td>02901</td>
                                        <td>Invalid Currency Code</td>
                                      </tr>
                                      <tr> 
                                        <td>02902</td>
                                        <td>Invalid Action Code</td>
                                      </tr>	
                                      <tr> 
                                        <td>02903</td>
                                        <td>Invalid Card Number </td>
                                      </tr>	
                                      <tr> 
                                        <td>02904</td>
                                        <td>Invalid Bank Code</td>
                                      </tr>
                                      <tr> 
                                        <td>02905</td>
                                        <td>Invalid Account number</td>
                                      </tr>	
                                      <tr> 
                                        <td>02906</td>
                                        <td>Invalid card number or account id</td>
                                      </tr>	
                                      <tr> 
                                        <td>02907</td>
                                        <td>Invalid account status</td>
                                      </tr>
                                      <tr> 
                                        <td>02908</td>
                                        <td>Invalid account Type</td>
                                      </tr>	
                                      <tr> 
                                        <td>02909</td>
                                        <td>Error Adding new account</td>
                                      </tr>
                                      <tr> 
                                        <td>02910</td>
                                        <td>Error while updating account </td>
                                      </tr>
                                      <tr> 
                                        <td>02911</td>
                                        <td>Error updating account status</td>
                                      </tr>									
                                      <tr> 
                                        <td>02912</td>
                                        <td>Invalid Account Bank Agency</td>
                                      </tr>	
                                </table>
                        </div> 
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/UpdateBankAccountV35Rs'
                  application/xml:
                    schema:
                      $ref: '#/components/schemas/UpdateBankAccountV35Rs'
 # Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>      
  schemas:
    # --- Import UpdateBankAccount request and response definition 
      UpdateBankAccountV35Rq:
          $ref: 'request.yaml#/UpdateBankAccountV35Rq'
      UpdateBankAccountV35Rs:
          $ref: 'response.yaml#/UpdateBankAccountV35Rs'
security:
  - bearerAuth: []