openapi: "3.0.3"
info:
  title: Financial account API documentation
  description: <div><p>Financial account operation management include features for :Financial account, Account transactions and Statements list.</p>
  version: PowerCARD-Issuer V3.5
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:
  #UpdateBankAccountStatus     
  /UpdateInterestRateIndex_V35/V2:
        post:
            description:
                        <h3>API Overview</h3>
                          <p>
                          Banks or any financial institution can use this service to adjust the interest rate applmied to a given account. This opretaion may result in descresing or increasing the interest arate applied. The new interest rate will be effective starting from the effective date part of the requiest message. Before that date it is the old interest rate index that will still be used until that date. 
                          </p>
                        <h3>Functional Description</h3>
                        <img  src="./docs/UpdateInterestRateIndex.png" />
            summary: Adjust the interest rate applied to a given account.
            tags:
              - Update Interest Rate Index
            requestBody:
              required: true
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/UpdateInterestRateIndex35Rq'
                application/xml:
                  schema:
                    $ref: '#/components/schemas/UpdateInterestRateIndex35Rq'
            responses:  
              200:
                description:
                        <div>
                                Successful
                                <p>Business Error Codes &#58;</p>
                                <table>
                                      <tr>
                                        <th>Error code</th>
                                        <th>Error Description</th>
                                      </tr>
                                      <tr> 
                                        <td>17201</td>
                                        <td>Invalid Interest rate index</td>
                                      </tr>
                                       <tr> 
                                        <td>17202</td>
                                        <td>Invalid Account number</td>
                                      </tr>
                                      <tr> 
                                        <td>17203</td>
                                        <td>Invalid Effective Date</td>
                                      </tr>                                           
                                </table>
                        </div> 
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/UpdateInterestRateIndex35Rs' 
                  application/xml:
                          schema:
                            $ref: '#/components/schemas/UpdateInterestRateIndex35Rs'
 # Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>      
  schemas:
    # --- Import UpdateBankAccountStatus35Rq request and response
      UpdateInterestRateIndex35Rq:
               $ref: 'request.yaml#/UpdateInterestRateIndex35Rq'  
      UpdateInterestRateIndex35Rs:
               $ref: 'response.yaml#/UpdateInterestRateIndex35Rs'
security:
  - bearerAuth: []