openapi: "3.0.3"
info:
  title: Loyalty API documentation
  description: <p>Loyalty account APIs provides access from any loyalty account record to Loyalty transactions, Loyalty account statements...</p>
  version: PowerCARD-Issuer V3.5
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:
  #getLoyaltyAccountTransactions  
  /GetLoyaltyAccTrxs/V2:
        post:
            description:
                        <h3>API Overview</h3>
                          <p>
                          Loyalty programs can help financial institution to increase their volume of card transaction because it builds a profitable relationship between the financial institutions and their customers.  By using its card for shopping the customers can earn points that he can redeem later for gifts, miles, discounts, cash-back, coupons, etc…
                          </p>
                          <p>
                          The current service is intended to send back the list of points earned by the customer within a range of date. Each transaction must contain information’s with regards to the shopping made by the customers as well as the number of points earned in that program. 
                          </p>
                        <h3>Functional Description</h3>
                       <img  src="./docs/getLoyaltyAccountTransactions.png" />
            summary: Get Loyalty Account Transactions.
            tags:
              - Get Loyalty Account Transactions.
            requestBody:
              required: true
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/GetLoyaltyAccountTransactionsV35Rq'
                application/xml:
                  schema:
                    $ref: '#/components/schemas/GetLoyaltyAccountTransactionsV35Rq'
            responses:  
              200:
                description:
                        <div>
                                Successful
                                <p>Business Error Codes &#58;</p>
                                <table>
                                      <tr>
                                        <th>Error code</th>
                                        <th>Error Description</th>
                                      </tr>
                                      <tr>
                                          <td>13101</td>
                                          <td>Invalid Account Owner Type</td>
                                      </tr>
                                      <tr>
                                          <td>13102</td>
                                          <td>Invalid Account Owner Id</td>
                                      </tr> 
                                      <tr>
                                          <td>13103</td>
                                          <td>Invalid range date</td>
                                      </tr>                                                                             
                                </table>
                        </div> 
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/GetLoyaltyAccountTransactionsV35Rs'
                  application/xml:
                      schema:
                        $ref: '#/components/schemas/GetLoyaltyAccountTransactionsV35Rs'  
 # Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>      
  schemas:
    # --- Import GetLoyaltyAccountTransactionsV35 request and response
      GetLoyaltyAccountTransactionsV35Rq:
               $ref: 'request.yaml#/GetLoyaltyAccountTransactionsV35Rq'
      GetLoyaltyAccountTransactionsV35Rs:
               $ref: 'response.yaml#/GetLoyaltyAccountTransactionsV35Rs'   
security:
  - bearerAuth: []