openapi: "3.0.3"
info:
  title: Loyalty API documentation
  description: <p>Loyalty account APIs provides access from any loyalty account record to Loyalty transactions, Loyalty account statements...</p>
  version: PowerCARD-Issuer V3.5
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:
  #LoyaltyAccounts  
  /LoyaltyAccounts/V2:
        get:
            description:
                        <h3>API Overview</h3>
                        <p>
                             In loyalty programs, for each dollar amount  spent, the cardholder can earn a number of points. He can for instance use those points as credit against future purchases. This web service was introduced to help customers as well as agent to display all the loyalty accounts linked to a given card. It also helps checking their loyalty account balance. The response will include for reach loyalty account, the name of the subscribed loyalty program, the number of outstanding points in the account, and some more details. Needless to mention that, the loyalty balance takes into consideration the eared points and also the redeemed ones.
                        </p>
                        <h3>Functional Description</h3>
                        <img  src="./docs/GetLoyaltyAccounts.png" />
            summary: Display all the loyalty accounts linked to a given card.
            tags:
              - Get LoyaltyAccounts.
            parameters:
              - in: query
                name: bankCode 
                schema:
                  type: string
                description: The bankCode value.
              - in: query
                name: accountOwnerType 
                schema:
                  type: string
                description: The accountOwnerType value.
              - in: query
                name: accountOwnerId 
                schema:
                  type: string
                description: The accountOwnerId value.
              - in: query
                name: LoyaltyAccountNbr 
                schema:
                  type: string
                description: The LoyaltyAccountNbr value.
              - in: query
                name: rangeStartDt 
                schema:
                  type: string
                description: The rangeStartDt value.
              - in: query
                name: rangeEndtDt 
                schema:
                  type: string
                description: The rangeEndtDt value.
              - in: query
                name: requestUID 
                schema:
                  type: string
                description: Request Identifier. It is sent by the calling system as a universally unique identifier for the message. Used to match response with request messages.
              - in: query
                name: requestDate 
                schema:
                  type: string
                description: Date when the request was submitted.
              - in: query
                name: userID 
                schema:
                  type: string
                description: Represents the user Id who made the request.
            responses:  
              200:
                description:
                    <div>
                            Successful
                            <p>Business Error Codes &#58;</p>
                            <table>
                                  <tr>
                                    <th>Error code</th>
                                    <th>Error Description</th>
                                  </tr>
                                  <tr> 
                                    <td>12801</td>
                                    <td>Invalid Account Owner Type</td>
                                  </tr>
                                  <tr> 
                                    <td>12802</td>
                                    <td>Invalid Account Owner Id</td>
                                  </tr>	
                                  <tr> 
                                    <td>12803</td>
                                    <td>No loyalty account defined for this entity</td>
                                  </tr>	
                                  <tr> 
                                    <td>12804</td>
                                    <td>Invalid Bank Code</td>
                                  </tr>									
                            </table>
                    </div> 
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/GetLoyaltyAccountsV35Rs'
                  application/xml:
                      schema:
                        $ref: '#/components/schemas/GetLoyaltyAccountsV35Rs'     
 # Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>      
  schemas:
      GetLoyaltyAccountsV35Rs:
            $ref: 'response.yaml#/GetLoyaltyAccountsV35Rs'
security:
  - bearerAuth: []