openapi: "3.0.3"
info:
  title: Customer API documentation
  description: <p>PowerCARD Connect’API offers through APIs specific functions that group in a functional logic, all features relating to Client operations management.</p>
  version: PowerCARD-Issuer 3.5.4-apiR5.3
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:
  # --- GetEventNotificationList
  /GetEventNotificationList/V2:
        post:
            description:
                        <h3>API Overview</h3>
                         <a target="_blank" rel="noopener noreferrer" href="https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/jaxws/GetEventNotificationList/V2?wsdl"><img  src="./docs/soap_logo.jpg" /><u>SOAP WSDL</u></a>
                          <p>
                               This web service is used to get the list of notification events, and their channels alongs with the activation status for each event and channel preferences. An event might be active or inactive. An event might have multiple channels (Email, SMS, …). Channel might have permanent and temporary preferences.
                          </p>
                        <h3>Functional Description</h3>
                         <img  src="./docs/GetEventNotificationList.png" />
            summary: Get the list of notification events, channels, activation status and channel preferences. 
            tags:
              - Get Event Notification List.
            requestBody:
              required: true
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/GetEventNotificationV35Rq'
                application/xml:
                  schema:
                    $ref: '#/components/schemas/GetEventNotificationV35Rq'
            responses:  
              200:
                description:
                        <div>
                                Successful
                                <p>Business Error Codes &#58;</p>
                                <table>
                                      <tr>
                                        <th>Error code</th>
                                        <th>Error Description</th>
                                      </tr>
                                      <tr> 
                                        <td>31301</td>
                                        <td>Invalid Entity Code</td>
                                      </tr>	
                                      <tr> 
                                        <td>31302</td>
                                        <td>Invalid Client Code</td>
                                      </tr>
                                      <tr> 
                                        <td>31303</td>
                                        <td>Invalid Card Number/ Token Ide</td>
                                      </tr>
                                      <tr> 
                                        <td>31304</td>
                                        <td>Invalid Account Id</td>
                                      </tr>								
                                </table>
                        </div> 
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/GetEventNotificationV35Rs'
                  application/xml:
                    schema:
                      $ref: '#/components/schemas/GetEventNotificationV35Rs'
# Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>      
  schemas:
    # --- Import SetCustomerDetailV35 request and response definition
      GetEventNotificationV35Rq:
            $ref: 'request.yaml#/GetEventNotificationV35Rq'
      GetEventNotificationV35Rs:
            $ref: 'response.yaml#/GetEventNotificationV35Rs'    
security:
  - bearerAuth: []