openapi: "3.0.3"
info:
  title: Customer API documentation
  description: <p>PowerCARD Connect’API offers through APIs specific functions that group in a functional logic, all features relating to Client operations management.</p>
  version: PowerCARD-Issuer 3.5.4-apiR5.3
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:
  #SearchCollaborators    
  /SearchCollaborators/V2:
        post:
            description:
                        <h3>API Overview</h3>
                          <p>
                            This API is used to get the list of non client employees for a particular corporate.<br>
                            The following sections are intended to highlight the process as well as the technical specification of the request and response messages.  
                          </p>
                        <h3>Functional Description</h3>
                        <img  src="./docs/SearchCollaborators.png" />
            summary:  This API is used to get the list of non client employees for a particular corporate.
            tags:
              - Search Collaborators
            requestBody:
              required: true
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/SearchCollaboratorsV35Rq'
                application/xml:
                  schema:
                    $ref: '#/components/schemas/SearchCollaboratorsV35Rq'
            responses:  
              200:
                description:
                        <div>
                                Successful
                                <p>Business Error Codes &#58;</p>
                                <table>
                                      <tr>
                                        <th>Error code</th>
                                        <th>Error Description</th>
                                      </tr>
                                      <tr>
                                        <td>30701</td>
                                        <td>Invalid Corporate ID</td>
                                      </tr>
                                       <tr>
                                        <td>30702</td>
                                        <td>Invalid Employee ID</td>
                                      </tr>
                                </table>
                        </div> 
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/SearchCollaboratorsV35Rs'
                  application/xml:
                    schema:
                      $ref: '#/components/schemas/SearchCollaboratorsV35Rs'                           
# Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>      
  schemas:
      SearchCollaboratorsV35Rq:
            $ref: 'request.yaml#/SearchCollaboratorsV35Rq'
      SearchCollaboratorsV35Rs:
            $ref: 'response.yaml#/SearchCollaboratorsV35Rs'    
security:
  - bearerAuth: []