openapi: "3.0.3"
info:
  title: Customer API documentation
  description: <p>PowerCARD Connect’API offers through APIs specific functions that group in a functional logic, all features relating to Client operations management.</p>
  version: PowerCARD-Issuer 3.5.4-apiR5.3
servers:
  - url: https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/rest
    description: Development server
paths:
  # --- UpdateCustomerCategory
  /UpdateCustomerCategory/V2:
        post:
            description:
                        <h3>API Overview</h3>
                          <a target="_blank" rel="noopener noreferrer" href="https://sandbox.connectapi.hps-worldwide.com/PowerCardConnectApi/jaxws/UpdateCustomerCategory/V2?wsdl"><img  src="./docs/soap_logo.jpg" /><u>SOAP WSDL</u></a>
                          <p>
                              The current web service could be used as a way to change some characteristics of an existing customer in PowerCARD system. It is mainly used by the agent in the bank desiring to apply a change a customer characteristic like its customer category.
                          </p>
                        <h3>Functional Description</h3>
                         <img  src="./docs/UpdateCustomerCategory.png" />
            summary: Change some characteristics of an existing customer.
            tags:
              - Update Customer Category.
            requestBody:
              required: true
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/UpdateCustomerCategoryV35Rq'
                application/xml:
                  schema:
                    $ref: '#/components/schemas/UpdateCustomerCategoryV35Rq'
            responses:  
              200:
                description:
                        <div>
                                Successful
                                <p>Business Error Codes &#58;</p>
                                <table>
                                    <tr>
                                      <th>Error code</th>
                                      <th>Error Description</th>
                                    </tr>
                                    <tr> 
                                      <td>03601</td>
                                      <td>Invalid Customer Id</td>
                                    </tr>	
                                    <tr> 
                                      <td>03602</td>
                                      <td>Invalid Customer Segment</td>
                                    </tr>								
                                </table>
                        </div>
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/UpdateCustomerCategoryV35Rs'
                  application/xml:
                    schema:
                      $ref: '#/components/schemas/UpdateCustomerCategoryV35Rs'                                      
# Components definition
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 
          <div>
               <h5>Api key authorization</h5>
               <p>JWT authorization header using Bearer scheme. Example &#8282; "Authorization &#8282; Bearer {token}"</p>
               <table>
                  <tr>
                      <td>Name &#8282;</td>
                      <td>Authorization</td>
                  </tr>
                   <tr>
                      <td>In &#8282;</td>
                      <td>Header</td>
                  </tr>
                </table>
          </div>      
  schemas:
      UpdateCustomerCategoryV35Rq:
            $ref: 'request.yaml#/UpdateCustomerCategoryV35Rq'
      UpdateCustomerCategoryV35Rs:
            $ref: 'response.yaml#/UpdateCustomerCategoryV35Rs'
security:
  - bearerAuth: []